import {readFileSync, writeFileSync} from 'node:fs'
import {resolve} from 'node:path'

const SOURCE_ENCODING = 'latin1'
const EXPECTED_HEADER = 'subclasse;subclasse_desc'
const CNAE_LENGTH = 7
const DEFAULT_SOURCE = '../tmp/subclassecnae.csv'
const DEFAULT_OUTPUT = 'src/lib/data/cnae.ts'

const sourcePath = resolve(process.cwd(), process.argv[2] ?? DEFAULT_SOURCE)
const outputPath = resolve(process.cwd(), process.argv[3] ?? DEFAULT_OUTPUT)
const [header, ...rows] = readFileSync(sourcePath, SOURCE_ENCODING)
  .replaceAll('\r', '')
  .trim()
  .split('\n')

if (header !== EXPECTED_HEADER) {
  throw new Error(`Cabeçalho CNAE inesperado: ${header}`)
}

const entries = rows.map((row, index) => {
  const separator = row.indexOf(';')
  if (separator < 0) {
    throw new Error(`Linha ${index + 2} sem separador`)
  }
  const rawCode = row.slice(0, separator).trim()
  const description = row.slice(separator + 1).trim()
  if (!/^\d{6,7}$/.test(rawCode) || !description) {
    throw new Error(`Linha ${index + 2} inválida: ${row}`)
  }
  return {code: rawCode.padStart(CNAE_LENGTH, '0'), description}
})

const codes = new Set(entries.map(({code}) => code))
if (codes.size !== entries.length) {
  throw new Error('O arquivo contém códigos CNAE duplicados após a normalização')
}

const generated = `// Code generated by scripts/generate-cnae.mjs from tmp/subclassecnae.csv. DO NOT EDIT.\n\n` +
  `export interface CnaeEntry {\n  code: string\n  description: string\n}\n\n` +
  `export const ALL_CNAES: readonly CnaeEntry[] = ${JSON.stringify(entries, null, 2)}\n`

writeFileSync(outputPath, generated, 'utf8')
console.log(`Gerados ${entries.length} CNAEs em ${outputPath}`)
