/var/log/app/app.log
/var/log/app/access.log
/var/log/nginx/access.log
/var/log/nginx/error.log {
    daily
    compress
    copytruncate
    missingok
    notifempty
    dateext
    dateformat -%Y%m%d
    rotate 1
    sharedscripts
    postrotate
        /opt/app/upload-logs.sh
    endscript
}
