// AUTO-GENERATED by scripts/generate-icms-lookup.js — do not edit manually

export interface IcmsNcmEntry {
  /** NCM digits only, no punctuation */
  ncm: string
  /** Effective ICMS rate as string with 4 decimal places, e.g. "17.0000" */
  aliq: string
  /** FCP rate if applicable */
  fcp: string | null
}

/** NCM-specific ICMS rates per UF, sorted longest-match-first */
const ICMS_NCM_BY_UF: Record<string, IcmsNcmEntry[]> = {
}

/**
 * Returns the most specific ICMS rate for a given UF and NCM code.
 * NCM is matched by prefix (chapter → heading → subheading → full code).
 * Returns null if no specific rate is found for this UF/NCM combination.
 */
export function getIcmsForNcm(uf: string, ncm: string): IcmsNcmEntry | null {
  const entries = ICMS_NCM_BY_UF[uf]
  if (!entries) return null
  const digits = ncm.replace(/\D/g, '')
  if (!digits) return null
  // Entries are sorted longest-first so the first match is the most specific
  return entries.find(e => digits.startsWith(e.ncm)) ?? null
}
