// Code generated by go-dfe/nfse/tables/gen/generate.py. DO NOT EDIT.

// Reexport dos motivos a partir do catálogo único de domínios fechados.
export type { NfseEnumOption as NfseMotiveOption } from './nfse_enums';
export {
  NFSE_THIRD_PARTY_MOTIVES,
  NFSE_CANCELLATION_MOTIVES,
  NFSE_FISCAL_ANALYSIS_MOTIVES,
  NFSE_SUBSTITUTION_MOTIVES,
  NFSE_REJECTION_MOTIVES,
} from './nfse_enums';
