// Code generated by go-dfe/nfse/tables/gen/generate.py. DO NOT EDIT.

export interface NfseEnumOption { value: string; label: string }

/** Catálogo completo dos domínios fechados do XSD, pela chave do tipo. */
export const NFSE_ENUMS: Record<string, readonly NfseEnumOption[]> = {
  "TBMISSQN": [
    {
      "value": "1",
      "label": "Isenção"
    },
    {
      "value": "2",
      "label": "Redução da BC em 'ppBM' %"
    },
    {
      "value": "3",
      "label": "Redução da BC em R$ 'vInfoBM'"
    },
    {
      "value": "4",
      "label": "Alíquota Diferenciada de 'aliqDifBM' %"
    }
  ],
  "TCObjetoLocacao": [
    {
      "value": "1",
      "label": "Ferrovia"
    },
    {
      "value": "2",
      "label": "Rodovia"
    },
    {
      "value": "3",
      "label": "Postes"
    },
    {
      "value": "4",
      "label": "Cabos"
    },
    {
      "value": "5",
      "label": "Dutos"
    },
    {
      "value": "6",
      "label": "Condutos de qualquer natureza"
    }
  ],
  "TSAmbGeradorEvt": [
    {
      "value": "1",
      "label": "Prefeitura"
    },
    {
      "value": "2",
      "label": "Sefin Nacional"
    },
    {
      "value": "3",
      "label": "Ambiente Nacional"
    }
  ],
  "TSAmbGeradorNFSe": [
    {
      "value": "1",
      "label": "Prefeitura"
    },
    {
      "value": "2",
      "label": "Sistema Nacional da NFS-e"
    }
  ],
  "TSCategVeic": [
    {
      "value": "00",
      "label": "Categoria de veículos (tipo não informado na nota de origem)"
    },
    {
      "value": "01",
      "label": "Automóvel, caminhonete e furgão"
    },
    {
      "value": "02",
      "label": "Caminhão leve, ônibus, caminhão trator e furgão"
    },
    {
      "value": "03",
      "label": "Automóvel e caminhonete com semireboque"
    },
    {
      "value": "04",
      "label": "Caminhão, caminhão-trator, caminhão-trator com semi-reboque e ônibus"
    },
    {
      "value": "05",
      "label": "Automóvel e caminhonete com reboque"
    },
    {
      "value": "06",
      "label": "Caminhão com reboque"
    },
    {
      "value": "07",
      "label": "Caminhão trator com semi-reboque"
    },
    {
      "value": "08",
      "label": "Motocicletas, motonetas e bicicletas motorizadas"
    },
    {
      "value": "09",
      "label": "Veículo especial"
    },
    {
      "value": "10",
      "label": "Veículo Isento"
    }
  ],
  "TSCategoriaServico": [
    {
      "value": "1",
      "label": "Locação"
    },
    {
      "value": "2",
      "label": "Sublocação"
    },
    {
      "value": "3",
      "label": "Arrendamento"
    },
    {
      "value": "4",
      "label": "Direito de passagem"
    },
    {
      "value": "5",
      "label": "Permissão de uso"
    }
  ],
  "TSCodAutorManifestacao": [
    {
      "value": "1",
      "label": "Prestador"
    },
    {
      "value": "2",
      "label": "Tomador"
    },
    {
      "value": "3",
      "label": "Intermediário"
    }
  ],
  "TSCodJustAnaliseFiscalCanc": [
    {
      "value": "1",
      "label": "Erro na Emissão"
    },
    {
      "value": "2",
      "label": "Serviço não Prestado"
    },
    {
      "value": "9",
      "label": "Outros"
    }
  ],
  "TSCodJustAnaliseFiscalCancDef": [
    {
      "value": "1",
      "label": "Cancelamento Extemporâneo Deferido"
    }
  ],
  "TSCodJustAnaliseFiscalCancIndef": [
    {
      "value": "1",
      "label": "Cancelamento Extemporâneo Indeferido"
    },
    {
      "value": "2",
      "label": "Cancelamento Extemporâneo Indeferido Sem Análise de Mérito"
    }
  ],
  "TSCodJustCanc": [
    {
      "value": "1",
      "label": "Erro na Emissão"
    },
    {
      "value": "2",
      "label": "Serviço não Prestado"
    },
    {
      "value": "9",
      "label": "Outros"
    }
  ],
  "TSCodJustSubst": [
    {
      "value": "01",
      "label": "Desenquadramento de NFS-e do Simples Nacional"
    },
    {
      "value": "02",
      "label": "Enquadramento de NFS-e no Simples Nacional"
    },
    {
      "value": "03",
      "label": "Inclusão Retroativa de Imunidade/Isenção para NFS-e"
    },
    {
      "value": "04",
      "label": "Exclusão Retroativa de Imunidade/Isenção para NFS-e"
    },
    {
      "value": "05",
      "label": "Rejeição de NFS-e pelo tomador ou pelo intermediário se responsável pelo recolhimento do tributo"
    },
    {
      "value": "99",
      "label": "Outros"
    }
  ],
  "TSCodMotivoRejeicao": [
    {
      "value": "1",
      "label": "NFS-e em duplicidade"
    },
    {
      "value": "2",
      "label": "NFS-e já emitida pelo tomador"
    },
    {
      "value": "3",
      "label": "Não ocorrência do fato gerador"
    },
    {
      "value": "4",
      "label": "Erro quanto a responsabilidade tributária"
    },
    {
      "value": "5",
      "label": "Erro quanto ao valor do serviço, valor das deduções ou serviço prestado ou data do fato gerador"
    },
    {
      "value": "9",
      "label": "Outros"
    }
  ],
  "TSCodNaoNIF": [
    {
      "value": "0",
      "label": "Não informado na nota de origem"
    },
    {
      "value": "1",
      "label": "Dispensado do NIF"
    },
    {
      "value": "2",
      "label": "Não exigência do NIF"
    }
  ],
  "TSEmitenteDPS": [
    {
      "value": "1",
      "label": "Prestador"
    },
    {
      "value": "2",
      "label": "Tomador"
    },
    {
      "value": "3",
      "label": "Intermediário"
    }
  ],
  "TSEnvMDIC": [
    {
      "value": "0",
      "label": "Não enviar para o MDIC"
    },
    {
      "value": "1",
      "label": "Enviar para o MDIC"
    }
  ],
  "TSIdeDedRed": [
    {
      "value": "1",
      "label": "Alimentação e bebidas/frigobar"
    },
    {
      "value": "2",
      "label": "Materiais"
    },
    {
      "value": "3",
      "label": "Produção Externa"
    },
    {
      "value": "4",
      "label": "Reembolso de despesas"
    },
    {
      "value": "5",
      "label": "Repasse consorciado"
    },
    {
      "value": "6",
      "label": "Repasse plano de saúde"
    },
    {
      "value": "7",
      "label": "Serviços"
    },
    {
      "value": "8",
      "label": "Subempreitada de mão de obra"
    },
    {
      "value": "9",
      "label": "Profissional parceiro"
    },
    {
      "value": "99",
      "label": "Outras deduções"
    }
  ],
  "TSMecAFComExPrest": [
    {
      "value": "00",
      "label": "Desconhecido (tipo não informado na nota de origem)"
    },
    {
      "value": "01",
      "label": "Nenhum"
    },
    {
      "value": "02",
      "label": "ACC - Adiantamento sobre Contrato de Câmbio – Redução a Zero do IR e do IOF"
    },
    {
      "value": "03",
      "label": "ACE – Adiantamento sobre Cambiais Entregues - Redução a Zero do IR e do IOF"
    },
    {
      "value": "04",
      "label": "BNDES-Exim Pós-Embarque – Serviços"
    },
    {
      "value": "05",
      "label": "BNDES-Exim Pré-Embarque - Serviços"
    },
    {
      "value": "06",
      "label": "FGE - Fundo de Garantia à Exportação"
    },
    {
      "value": "07",
      "label": "PROEX - EQUALIZAÇÃO"
    },
    {
      "value": "08",
      "label": "PROEX - Financiamento"
    }
  ],
  "TSMecAFComExToma": [
    {
      "value": "00",
      "label": "Desconhecido (tipo não informado na nota de origem)"
    },
    {
      "value": "01",
      "label": "Nenhum"
    },
    {
      "value": "02",
      "label": "Adm. Pública e Repr. Internacional"
    },
    {
      "value": "03",
      "label": "Alugueis e Arrend. Mercantil de maquinas, equip., embarc. e aeronaves"
    },
    {
      "value": "04",
      "label": "Arrendamento Mercantil de aeronave para empresa de transporte aéreo público"
    },
    {
      "value": "05",
      "label": "Comissão a agentes externos na exportação"
    },
    {
      "value": "06",
      "label": "Despesas de armazenagem, mov. e transporte de carga no exterior"
    },
    {
      "value": "07",
      "label": "Eventos FIFA (subsidiária)"
    },
    {
      "value": "08",
      "label": "Eventos FIFA"
    },
    {
      "value": "09",
      "label": "Fretes, arrendamentos de embarcações ou aeronaves e outros"
    },
    {
      "value": "10",
      "label": "Material Aeronáutico"
    },
    {
      "value": "11",
      "label": "Promoção de Bens no Exterior"
    },
    {
      "value": "12",
      "label": "Promoção de Dest. Turísticos Brasileiros"
    },
    {
      "value": "13",
      "label": "Promoção do Brasil no Exterior"
    },
    {
      "value": "14",
      "label": "Promoção Serviços no Exterior"
    },
    {
      "value": "15",
      "label": "RECINE"
    },
    {
      "value": "16",
      "label": "RECOPA"
    },
    {
      "value": "17",
      "label": "Registro e Manutenção de marcas, patentes e cultivares"
    },
    {
      "value": "18",
      "label": "REICOMP"
    },
    {
      "value": "19",
      "label": "REIDI"
    },
    {
      "value": "20",
      "label": "REPENEC"
    },
    {
      "value": "21",
      "label": "REPES"
    },
    {
      "value": "22",
      "label": "RETAERO"
    },
    {
      "value": "23",
      "label": "RETID"
    },
    {
      "value": "24",
      "label": "Royalties, Assistência Técnica, Científica e Assemelhados"
    },
    {
      "value": "25",
      "label": "Serviços de avaliação da conformidade vinculados aos Acordos da OMC"
    },
    {
      "value": "26",
      "label": "ZPE"
    }
  ],
  "TSModoPrestacao": [
    {
      "value": "0",
      "label": "Desconhecido (tipo não informado na nota de origem)"
    },
    {
      "value": "1",
      "label": "Transfronteiriço"
    },
    {
      "value": "2",
      "label": "Consumo no Brasil"
    },
    {
      "value": "3",
      "label": "Presença Comercial no Exterior"
    },
    {
      "value": "4",
      "label": "Movimento Temporário de Pessoas Físicas"
    }
  ],
  "TSMotivoEmisTI": [
    {
      "value": "1",
      "label": "Importação de Serviço"
    },
    {
      "value": "2",
      "label": "Tomador/Intermediário obrigado a emitir NFS-e por legislação municipal"
    },
    {
      "value": "3",
      "label": "Tomador/Intermediário emitindo NFS-e por recusa de emissão pelo prestador"
    },
    {
      "value": "4",
      "label": "Tomador/Intermediário emitindo por rejeitar a NFS-e emitida pelo prestador"
    }
  ],
  "TSMovTempBens": [
    {
      "value": "0",
      "label": "Desconhecido (tipo não informado na nota de origem)"
    },
    {
      "value": "1",
      "label": "Não"
    },
    {
      "value": "2",
      "label": "Vinculada - Declaração de Importação"
    },
    {
      "value": "3",
      "label": "Vinculada - Declaração de Exportação"
    }
  ],
  "TSOpConsumServ": [
    {
      "value": "0",
      "label": "Consumo do serviço prestado ocorrido no município do local da prestação"
    },
    {
      "value": "1",
      "label": "Consumo do serviço prestado ocorrido ocorrido no exterior"
    }
  ],
  "TSOpExigSuspensa": [
    {
      "value": "1",
      "label": "Exigibilidade Suspensa por Decisão Judicial"
    },
    {
      "value": "2",
      "label": "Exigibilidade Suspensa por Processo Administrativo"
    }
  ],
  "TSOpSNLimUltrap": [
    {
      "value": "0",
      "label": "Não ultrapassado"
    },
    {
      "value": "1",
      "label": "Ultrapassado"
    }
  ],
  "TSOpSimpNac": [
    {
      "value": "1",
      "label": "Não Optante"
    },
    {
      "value": "2",
      "label": "Optante - Microempreendedor Individual (MEI)"
    },
    {
      "value": "3",
      "label": "Optante - Microempresa ou Empresa de Pequeno Porte (ME/EPP)"
    }
  ],
  "TSProcEmissao": [
    {
      "value": "1",
      "label": "Emissão com aplicativo do contribuinte (via Web Service)"
    },
    {
      "value": "2",
      "label": "Emissão com aplicativo disponibilizado pelo fisco (Web)"
    },
    {
      "value": "3",
      "label": "Emissão com aplicativo disponibilizado pelo fisco (App)"
    }
  ],
  "TSRTCFinNFSe": [
    {
      "value": "0",
      "label": "NFS-e regular"
    }
  ],
  "TSRTCIndDest": [
    {
      "value": "0",
      "label": "o destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador = adquirente = destinatário)"
    },
    {
      "value": "1",
      "label": "o destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador = adquirente ≠ destinatário)"
    }
  ],
  "TSRTCIndFinal": [
    {
      "value": "0",
      "label": "Não"
    },
    {
      "value": "1",
      "label": "Sim"
    }
  ],
  "TSRTCTipoChaveDFe": [
    {
      "value": "1",
      "label": "NFS-e"
    },
    {
      "value": "2",
      "label": "NF-e"
    },
    {
      "value": "3",
      "label": "CT-e"
    },
    {
      "value": "9",
      "label": "Outro"
    }
  ],
  "TSRTCTpEnteGov": [
    {
      "value": "1",
      "label": "União"
    },
    {
      "value": "2",
      "label": "Estado"
    },
    {
      "value": "3",
      "label": "Distrito Federal"
    },
    {
      "value": "4",
      "label": "Município"
    }
  ],
  "TSRTCTpOper": [
    {
      "value": "1",
      "label": "Fornecimento com pagamento posterior"
    },
    {
      "value": "2",
      "label": "Recebimento do pagamento com fornecimento já realizado"
    },
    {
      "value": "3",
      "label": "Fornecimento com pagamento já realizado"
    },
    {
      "value": "4",
      "label": "Recebimento do pagamento com fornecimento posterior"
    },
    {
      "value": "5",
      "label": "Fornecimento e recebimento do pagamento concomitantes"
    }
  ],
  "TSRTCTpReeRepRes": [
    {
      "value": "01",
      "label": "Repasse de remuneração por intermediação de imóveis a demais corretores envolvidos na operação"
    },
    {
      "value": "02",
      "label": "Repasse de valores a fornecedor relativo a fornecimento intermediado por agência de turismo"
    },
    {
      "value": "03",
      "label": "Reembolso ou ressarcimento recebido por agência de propaganda e publicidade por valores pagos relativos a serviços de produção externa por conta e ordem de terceiro"
    },
    {
      "value": "04",
      "label": "Reembolso ou ressarcimento recebido por agência de propaganda e publicidade por valores pagos relativos a serviços de mídia por conta e ordem de terceiro"
    },
    {
      "value": "99",
      "label": "Outros reembolsos ou ressarcimentos recebidos por valores pagos relativos a operações por conta e ordem de terceiro"
    }
  ],
  "TSRegEspTrib": [
    {
      "value": "0",
      "label": "Nenhum"
    },
    {
      "value": "1",
      "label": "Ato Cooperado (Cooperativa)"
    },
    {
      "value": "2",
      "label": "Estimativa"
    },
    {
      "value": "3",
      "label": "Microempresa Municipal"
    },
    {
      "value": "4",
      "label": "Notário ou Registrador"
    },
    {
      "value": "5",
      "label": "Profissional Autônomo"
    },
    {
      "value": "6",
      "label": "Sociedade de Profissionais"
    },
    {
      "value": "9",
      "label": "Outros"
    }
  ],
  "TSRegimeApuracaoSimpNac": [
    {
      "value": "1",
      "label": "Regime de apuração dos tributos federais e municipal pelo SN"
    },
    {
      "value": "2",
      "label": "Regime de apuração dos tributos federais pelo SN e ISSQN por fora do SN conforme respectiva legislação municipal do tributo"
    },
    {
      "value": "3",
      "label": "Regime de apuração dos tributos federais e municipal por fora do SN conforme respectivas legislações federal e municipal de cada tributo"
    }
  ],
  "TSRodagem": [
    {
      "value": "1",
      "label": "Simples"
    },
    {
      "value": "2",
      "label": "Dupla"
    }
  ],
  "TSSituacaoEmissaoNFSE": [
    {
      "value": "0",
      "label": "Não Habilitado"
    },
    {
      "value": "1",
      "label": "Habilitado"
    }
  ],
  "TSTipoAmbiente": [
    {
      "value": "1",
      "label": "Produção"
    },
    {
      "value": "2",
      "label": "Homologação"
    }
  ],
  "TSTipoCST": [
    {
      "value": "00",
      "label": "Nenhum"
    },
    {
      "value": "01",
      "label": "Operação Tributável com Alíquota Básica"
    },
    {
      "value": "02",
      "label": "Operação Tributável com Alíquota Diferenciada"
    },
    {
      "value": "03",
      "label": "Operação Tributável com Alíquota por Unidade de Medida de Produto"
    },
    {
      "value": "04",
      "label": "Operação Tributável monofásica - Revenda a Alíquota Zero"
    },
    {
      "value": "05",
      "label": "Operação Tributável por Substituição Tributária"
    },
    {
      "value": "06",
      "label": "Operação Tributável a Alíquota Zero"
    },
    {
      "value": "07",
      "label": "Operação Isenta da Contribuição"
    },
    {
      "value": "08",
      "label": "Operação sem Incidência da Contribuição"
    },
    {
      "value": "09",
      "label": "Operação com Suspensão da Contribuição"
    },
    {
      "value": "49",
      "label": "Outras Operações de Saída"
    },
    {
      "value": "50",
      "label": "Operação com Direito a Crédito – Vinculada Exclusivamente a Receita Tributada no Mercado Interno"
    },
    {
      "value": "51",
      "label": "Operação com Direito a Crédito – Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno"
    },
    {
      "value": "52",
      "label": "Operação com Direito a Crédito – Vinculada Exclusivamente a Receita de Exportação"
    },
    {
      "value": "53",
      "label": "Operação com Direito a Crédito – Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno"
    },
    {
      "value": "54",
      "label": "Operação com Direito a Crédito – Vinculada a Receitas Tributadas no Mercado Interno e de Exportação"
    },
    {
      "value": "55",
      "label": "Operação com Direito a Crédito – Vinculada a Receitas Não Tributadas no Mercado Interno e de Exportação"
    },
    {
      "value": "56",
      "label": "Operação com Direito a Crédito – Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno e de Exportação"
    },
    {
      "value": "60",
      "label": "Crédito Presumido – Operação de Aquisição Vinculada Exclusivamente a Receita Tributada no Mercado Interno"
    },
    {
      "value": "61",
      "label": "Crédito Presumido – Operação de Aquisição Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno"
    },
    {
      "value": "62",
      "label": "Crédito Presumido – Operação de Aquisição Vinculada Exclusivamente a Receita de Exportação"
    },
    {
      "value": "63",
      "label": "Crédito Presumido – Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno"
    },
    {
      "value": "64",
      "label": "Crédito Presumido – Operação de Aquisição Vinculada a Receitas Tributadas no Mercado Interno e de Exportação"
    },
    {
      "value": "65",
      "label": "Crédito Presumido – Operação de Aquisição Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação"
    },
    {
      "value": "66",
      "label": "Crédito Presumido – Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno e de Exportação"
    },
    {
      "value": "67",
      "label": "Crédito Presumido – Outras Operações"
    },
    {
      "value": "70",
      "label": "Operação de Aquisição sem Direito a Crédito"
    },
    {
      "value": "71",
      "label": "Operação de Aquisição com Isenção"
    },
    {
      "value": "72",
      "label": "Operação de Aquisição com Suspensão"
    },
    {
      "value": "73",
      "label": "Operação de Aquisição a Alíquota Zero"
    },
    {
      "value": "74",
      "label": "Operação de Aquisição sem Incidência da Contribuição"
    },
    {
      "value": "75",
      "label": "Operação de Aquisição por Substituição Tributária"
    },
    {
      "value": "98",
      "label": "Outras Operações de Entrada"
    },
    {
      "value": "99",
      "label": "Outras Operações"
    }
  ],
  "TSTipoEmissao": [
    {
      "value": "1",
      "label": "Emissão normal no modelo da NFS-e Nacional"
    },
    {
      "value": "2",
      "label": "Emissão original em leiaute próprio do município com transcrição para o modelo da NFS-e Nacional"
    }
  ],
  "TSTipoImunidadeISSQN": [
    {
      "value": "0",
      "label": "Imunidade (tipo não informado na nota de origem)"
    },
    {
      "value": "1",
      "label": "Patrimônio, renda ou serviços, uns dos outros (CF88, Art 150, VI, a)"
    },
    {
      "value": "2",
      "label": "Templos de qualquer culto (CF88, Art 150, VI, b)"
    },
    {
      "value": "3",
      "label": "Patrimônio, renda ou serviços dos partidos políticos, inclusive suas fundações, das entidades sindicais dos trabalhadores, das instituições de educação e de assistência social, sem fins lucrativos, atendidos os requisitos da lei (CF88, Art 150, VI, c)"
    },
    {
      "value": "4",
      "label": "Livros, jornais, periódicos e o papel destinado a sua impressão (CF88, Art 150, VI, d)"
    },
    {
      "value": "5",
      "label": "Fonogramas e videofonogramas musicais produzidos no Brasil contendo obras musicais ou literomusicais de autores brasileiros e/ou obras em geral interpretadas por artistas brasileiros bem como os suportes materiais ou arquivos digitais que os contenham, salvo na etapa de replicação industrial de mídias ópticas de leitura a laser. (CF88, Art 150, VI, e)"
    }
  ],
  "TSTipoIndTotTrib": [
    {
      "value": "0",
      "label": "Não"
    }
  ],
  "TSTipoRetISSQN": [
    {
      "value": "1",
      "label": "Não Retido"
    },
    {
      "value": "2",
      "label": "Retido pelo Tomador"
    },
    {
      "value": "3",
      "label": "Retido pelo Intermediario"
    }
  ],
  "TSTipoRetPISCofins": [
    {
      "value": "0",
      "label": "PIS/COFINS/CSLL Não Retidos"
    },
    {
      "value": "1",
      "label": "PIS/COFINS Retidos"
    },
    {
      "value": "2",
      "label": "PIS/COFINS Não Retidos"
    },
    {
      "value": "3",
      "label": "PIS/COFINS/CSLL Retidos"
    },
    {
      "value": "4",
      "label": "PIS/COFINS Retidos, CSLL Não Retido"
    },
    {
      "value": "5",
      "label": "PIS Retido, COFINS/CSLL Não Retido"
    },
    {
      "value": "6",
      "label": "COFINS Retido, PIS/CSLL Não Retido"
    },
    {
      "value": "7",
      "label": "PIS Não Retido, COFINS/CSLL Retidos"
    },
    {
      "value": "8",
      "label": "PIS/COFINS Não Retidos, CSLL Retido"
    },
    {
      "value": "9",
      "label": "COFINS Não Retido, PIS/CSLL Retidos"
    }
  ],
  "TSTribISSQN": [
    {
      "value": "1",
      "label": "Operação tributável"
    },
    {
      "value": "2",
      "label": "Imunidade"
    },
    {
      "value": "3",
      "label": "Exportação de serviço"
    },
    {
      "value": "4",
      "label": "Não Incidência"
    }
  ],
  "TSVincPrest": [
    {
      "value": "0",
      "label": "Sem vínculo com o Tomador/Prestador"
    },
    {
      "value": "1",
      "label": "Controlada"
    },
    {
      "value": "2",
      "label": "Controladora"
    },
    {
      "value": "3",
      "label": "Coligada"
    },
    {
      "value": "4",
      "label": "Matriz"
    },
    {
      "value": "5",
      "label": "Filial ou sucursal"
    },
    {
      "value": "6",
      "label": "Outro vínculo"
    },
    {
      "value": "9",
      "label": "Desconhecido (tipo não informado na nota de origem)"
    }
  ],
  "TStat": [
    {
      "value": "100",
      "label": "NFS-e Gerada"
    },
    {
      "value": "102",
      "label": "NFS-e de Decisão Judicial"
    },
    {
      "value": "103",
      "label": "NFS-e Avulsa"
    },
    {
      "value": "107",
      "label": "NFS-e MEI"
    }
  ]
} as const;

export const NFSE_THIRD_PARTY_MOTIVES: readonly NfseEnumOption[] = NFSE_ENUMS.TSMotivoEmisTI;
export const NFSE_EMITENTE_DPS: readonly NfseEnumOption[] = NFSE_ENUMS.TSEmitenteDPS;
export const NFSE_NAO_NIF_REASONS: readonly NfseEnumOption[] = NFSE_ENUMS.TSCodNaoNIF;
export const NFSE_CANCELLATION_MOTIVES: readonly NfseEnumOption[] = NFSE_ENUMS.TSCodJustCanc;
export const NFSE_SUBSTITUTION_MOTIVES: readonly NfseEnumOption[] = NFSE_ENUMS.TSCodJustSubst;
export const NFSE_FISCAL_ANALYSIS_MOTIVES: readonly NfseEnumOption[] = NFSE_ENUMS.TSCodJustAnaliseFiscalCanc;
export const NFSE_REJECTION_MOTIVES: readonly NfseEnumOption[] = NFSE_ENUMS.TSCodMotivoRejeicao;
export const NFSE_MANIFESTATION_AUTHORS: readonly NfseEnumOption[] = NFSE_ENUMS.TSCodAutorManifestacao;
export const NFSE_MODO_PRESTACAO: readonly NfseEnumOption[] = NFSE_ENUMS.TSModoPrestacao;
export const NFSE_VINC_PREST: readonly NfseEnumOption[] = NFSE_ENUMS.TSVincPrest;
export const NFSE_MEC_AF_COMEX_PRESTADOR: readonly NfseEnumOption[] = NFSE_ENUMS.TSMecAFComExPrest;
export const NFSE_MEC_AF_COMEX_TOMADOR: readonly NfseEnumOption[] = NFSE_ENUMS.TSMecAFComExToma;
export const NFSE_MOV_TEMP_BENS: readonly NfseEnumOption[] = NFSE_ENUMS.TSMovTempBens;
export const NFSE_ENV_MDIC: readonly NfseEnumOption[] = NFSE_ENUMS.TSEnvMDIC;
export const NFSE_TRIB_ISSQN: readonly NfseEnumOption[] = NFSE_ENUMS.TSTribISSQN;
export const NFSE_TIPO_IMUNIDADE_ISSQN: readonly NfseEnumOption[] = NFSE_ENUMS.TSTipoImunidadeISSQN;
export const NFSE_TIPO_RET_ISSQN: readonly NfseEnumOption[] = NFSE_ENUMS.TSTipoRetISSQN;
export const NFSE_OP_EXIG_SUSPENSA: readonly NfseEnumOption[] = NFSE_ENUMS.TSOpExigSuspensa;
export const NFSE_BENEFICIO_MUNICIPAL: readonly NfseEnumOption[] = NFSE_ENUMS.TBMISSQN;
export const NFSE_OP_SIMP_NAC: readonly NfseEnumOption[] = NFSE_ENUMS.TSOpSimpNac;
export const NFSE_REG_APURACAO_SIMP_NAC: readonly NfseEnumOption[] = NFSE_ENUMS.TSRegimeApuracaoSimpNac;
export const NFSE_REG_ESP_TRIB: readonly NfseEnumOption[] = NFSE_ENUMS.TSRegEspTrib;
export const NFSE_IDE_DED_RED: readonly NfseEnumOption[] = NFSE_ENUMS.TSIdeDedRed;
export const NFSE_CST_PIS_COFINS: readonly NfseEnumOption[] = NFSE_ENUMS.TSTipoCST;
export const NFSE_TIPO_RET_PIS_COFINS: readonly NfseEnumOption[] = NFSE_ENUMS.TSTipoRetPISCofins;
export const NFSE_RTC_TP_OPER: readonly NfseEnumOption[] = NFSE_ENUMS.TSRTCTpOper;
export const NFSE_RTC_TP_ENTE_GOV: readonly NfseEnumOption[] = NFSE_ENUMS.TSRTCTpEnteGov;
export const NFSE_RTC_IND_DEST: readonly NfseEnumOption[] = NFSE_ENUMS.TSRTCIndDest;
export const NFSE_RTC_IND_FINAL: readonly NfseEnumOption[] = NFSE_ENUMS.TSRTCIndFinal;
export const NFSE_RTC_TP_REE_REP_RES: readonly NfseEnumOption[] = NFSE_ENUMS.TSRTCTpReeRepRes;
export const NFSE_TIPO_CHAVE_DFE: readonly NfseEnumOption[] = NFSE_ENUMS.TSRTCTipoChaveDFe;
