// Code generated by go-dfe/nfse/tables/gen/generate.py. DO NOT EDIT.

export interface TribNacionalEntry {
  code: string;
  item: string;
  subitem: string;
  desdobro: string;
  description: string;
}

export const NFSE_TRIB_NACIONAL: readonly TribNacionalEntry[] = [
  {
    "code": "010101",
    "item": "1",
    "subitem": "1",
    "desdobro": "1",
    "description": "Análise e desenvolvimento de sistemas."
  },
  {
    "code": "010201",
    "item": "1",
    "subitem": "2",
    "desdobro": "1",
    "description": "Programação."
  },
  {
    "code": "010301",
    "item": "1",
    "subitem": "3",
    "desdobro": "1",
    "description": "Processamento de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres."
  },
  {
    "code": "010302",
    "item": "1",
    "subitem": "3",
    "desdobro": "2",
    "description": "Armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres."
  },
  {
    "code": "010401",
    "item": "1",
    "subitem": "4",
    "desdobro": "1",
    "description": "Elaboração de programas de computadores, inclusive de jogos eletrônicos, independentemente da arquitetura construtiva da máquina em que o programa será executado, incluindo tablets, smartphones e congêneres."
  },
  {
    "code": "010501",
    "item": "1",
    "subitem": "5",
    "desdobro": "1",
    "description": "Licenciamento ou cessão de direito de uso de programas de computação."
  },
  {
    "code": "010601",
    "item": "1",
    "subitem": "6",
    "desdobro": "1",
    "description": "Assessoria e consultoria em informática."
  },
  {
    "code": "010701",
    "item": "1",
    "subitem": "7",
    "desdobro": "1",
    "description": "Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados."
  },
  {
    "code": "010801",
    "item": "1",
    "subitem": "8",
    "desdobro": "1",
    "description": "Planejamento, confecção, manutenção e atualização de páginas eletrônicas."
  },
  {
    "code": "010901",
    "item": "1",
    "subitem": "9",
    "desdobro": "1",
    "description": "Disponibilização, sem cessão definitiva, de conteúdos de áudio por meio da internet (exceto a distribuição de conteúdos pelas prestadoras de Serviço de Acesso Condicionado, de que trata a Lei nº 12.485, de 12 de setembro de 2011, sujeita ao ICMS)."
  },
  {
    "code": "010902",
    "item": "1",
    "subitem": "9",
    "desdobro": "2",
    "description": "Disponibilização, sem cessão definitiva, de conteúdos de vídeo, imagem e texto por meio da internet, respeitada a imunidade de livros, jornais e periódicos (exceto a distribuição de conteúdos pelas prestadoras de Serviço de Acesso Condicionado, de que trata a Lei nº 12.485, de 12 de setembro de 2011, sujeita ao ICMS)."
  },
  {
    "code": "020101",
    "item": "2",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de pesquisas e desenvolvimento de qualquer natureza."
  },
  {
    "code": "030201",
    "item": "3",
    "subitem": "2",
    "desdobro": "1",
    "description": "Cessão de direito de uso de marcas e de sinais de propaganda."
  },
  {
    "code": "030301",
    "item": "3",
    "subitem": "3",
    "desdobro": "1",
    "description": "Exploração de salões de festas, centro de convenções, stands e congêneres, para realização de eventos ou negócios de qualquer natureza."
  },
  {
    "code": "030302",
    "item": "3",
    "subitem": "3",
    "desdobro": "2",
    "description": "Exploração de escritórios virtuais e congêneres, para realização de eventos ou negócios de qualquer natureza."
  },
  {
    "code": "030303",
    "item": "3",
    "subitem": "3",
    "desdobro": "3",
    "description": "Exploração de quadras esportivas, estádios, ginásios, canchas e congêneres, para realização de eventos ou negócios de qualquer natureza."
  },
  {
    "code": "030304",
    "item": "3",
    "subitem": "3",
    "desdobro": "4",
    "description": "Exploração de auditórios, casas de espetáculos e congêneres, para realização de eventos ou negócios de qualquer natureza."
  },
  {
    "code": "030305",
    "item": "3",
    "subitem": "3",
    "desdobro": "5",
    "description": "Exploração de parques de diversões e congêneres, para realização de eventos ou negócios de qualquer natureza."
  },
  {
    "code": "030401",
    "item": "3",
    "subitem": "4",
    "desdobro": "1",
    "description": "Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de ferrovia."
  },
  {
    "code": "030402",
    "item": "3",
    "subitem": "4",
    "desdobro": "2",
    "description": "Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de rodovia."
  },
  {
    "code": "030403",
    "item": "3",
    "subitem": "4",
    "desdobro": "3",
    "description": "Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de postes, cabos, dutos e condutos de qualquer natureza."
  },
  {
    "code": "030501",
    "item": "3",
    "subitem": "5",
    "desdobro": "1",
    "description": "Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário."
  },
  {
    "code": "040101",
    "item": "4",
    "subitem": "1",
    "desdobro": "1",
    "description": "Medicina."
  },
  {
    "code": "040102",
    "item": "4",
    "subitem": "1",
    "desdobro": "2",
    "description": "Biomedicina."
  },
  {
    "code": "040201",
    "item": "4",
    "subitem": "2",
    "desdobro": "1",
    "description": "Análises clínicas e congêneres."
  },
  {
    "code": "040202",
    "item": "4",
    "subitem": "2",
    "desdobro": "2",
    "description": "Patologia e congêneres."
  },
  {
    "code": "040203",
    "item": "4",
    "subitem": "2",
    "desdobro": "3",
    "description": "Eletricidade médica (eletroestimulação de nervos e musculos, cardioversão, etc) e congêneres."
  },
  {
    "code": "040204",
    "item": "4",
    "subitem": "2",
    "desdobro": "4",
    "description": "Radioterapia, quimioterapia e congêneres."
  },
  {
    "code": "040205",
    "item": "4",
    "subitem": "2",
    "desdobro": "5",
    "description": "Ultra-sonografia, ressonância magnética, radiologia, tomografia e congêneres."
  },
  {
    "code": "040301",
    "item": "4",
    "subitem": "3",
    "desdobro": "1",
    "description": "Hospitais e congêneres."
  },
  {
    "code": "040302",
    "item": "4",
    "subitem": "3",
    "desdobro": "2",
    "description": "Laboratórios e congêneres."
  },
  {
    "code": "040303",
    "item": "4",
    "subitem": "3",
    "desdobro": "3",
    "description": "Clínicas, sanatórios, manicômios, casas de saúde, prontos-socorros, ambulatórios e congêneres."
  },
  {
    "code": "040401",
    "item": "4",
    "subitem": "4",
    "desdobro": "1",
    "description": "Instrumentação cirúrgica."
  },
  {
    "code": "040501",
    "item": "4",
    "subitem": "5",
    "desdobro": "1",
    "description": "Acupuntura."
  },
  {
    "code": "040601",
    "item": "4",
    "subitem": "6",
    "desdobro": "1",
    "description": "Enfermagem, inclusive serviços auxiliares."
  },
  {
    "code": "040701",
    "item": "4",
    "subitem": "7",
    "desdobro": "1",
    "description": "Serviços farmacêuticos."
  },
  {
    "code": "040801",
    "item": "4",
    "subitem": "8",
    "desdobro": "1",
    "description": "Terapia ocupacional."
  },
  {
    "code": "040802",
    "item": "4",
    "subitem": "8",
    "desdobro": "2",
    "description": "Fisioterapia."
  },
  {
    "code": "040803",
    "item": "4",
    "subitem": "8",
    "desdobro": "3",
    "description": "Fonoaudiologia."
  },
  {
    "code": "040901",
    "item": "4",
    "subitem": "9",
    "desdobro": "1",
    "description": "Terapias de qualquer espécie destinadas ao tratamento físico, orgânico e mental."
  },
  {
    "code": "041001",
    "item": "4",
    "subitem": "10",
    "desdobro": "1",
    "description": "Nutrição."
  },
  {
    "code": "041101",
    "item": "4",
    "subitem": "11",
    "desdobro": "1",
    "description": "Obstetrícia."
  },
  {
    "code": "041201",
    "item": "4",
    "subitem": "12",
    "desdobro": "1",
    "description": "Odontologia."
  },
  {
    "code": "041301",
    "item": "4",
    "subitem": "13",
    "desdobro": "1",
    "description": "Ortóptica."
  },
  {
    "code": "041401",
    "item": "4",
    "subitem": "14",
    "desdobro": "1",
    "description": "Próteses sob encomenda."
  },
  {
    "code": "041501",
    "item": "4",
    "subitem": "15",
    "desdobro": "1",
    "description": "Psicanálise."
  },
  {
    "code": "041601",
    "item": "4",
    "subitem": "16",
    "desdobro": "1",
    "description": "Psicologia."
  },
  {
    "code": "041701",
    "item": "4",
    "subitem": "17",
    "desdobro": "1",
    "description": "Casas de repouso e congêneres."
  },
  {
    "code": "041702",
    "item": "4",
    "subitem": "17",
    "desdobro": "2",
    "description": "Casas de recuperação e congêneres."
  },
  {
    "code": "041703",
    "item": "4",
    "subitem": "17",
    "desdobro": "3",
    "description": "Creches e congêneres."
  },
  {
    "code": "041704",
    "item": "4",
    "subitem": "17",
    "desdobro": "4",
    "description": "Asilos e congêneres."
  },
  {
    "code": "041801",
    "item": "4",
    "subitem": "18",
    "desdobro": "1",
    "description": "Inseminação artificial, fertilização in vitro e congêneres."
  },
  {
    "code": "041901",
    "item": "4",
    "subitem": "19",
    "desdobro": "1",
    "description": "Bancos de sangue, leite, pele, olhos, óvulos, sêmen e congêneres."
  },
  {
    "code": "042001",
    "item": "4",
    "subitem": "20",
    "desdobro": "1",
    "description": "Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie."
  },
  {
    "code": "042101",
    "item": "4",
    "subitem": "21",
    "desdobro": "1",
    "description": "Unidade de atendimento, assistência ou tratamento móvel e congêneres."
  },
  {
    "code": "042201",
    "item": "4",
    "subitem": "22",
    "desdobro": "1",
    "description": "Planos de medicina de grupo ou individual e convênios para prestação de assistência médica, hospitalar, odontológica e congêneres."
  },
  {
    "code": "042301",
    "item": "4",
    "subitem": "23",
    "desdobro": "1",
    "description": "Outros planos de saúde que se cumpram através de serviços de terceiros contratados, credenciados, cooperados ou apenas pagos pelo operador do plano mediante indicação do beneficiário."
  },
  {
    "code": "050101",
    "item": "5",
    "subitem": "1",
    "desdobro": "1",
    "description": "Medicina veterinária"
  },
  {
    "code": "050102",
    "item": "5",
    "subitem": "1",
    "desdobro": "2",
    "description": "Zootecnia."
  },
  {
    "code": "050201",
    "item": "5",
    "subitem": "2",
    "desdobro": "1",
    "description": "Hospitais e congêneres, na área veterinária."
  },
  {
    "code": "050202",
    "item": "5",
    "subitem": "2",
    "desdobro": "2",
    "description": "Clínicas, ambulatórios, prontos-socorros e congêneres, na área veterinária."
  },
  {
    "code": "050301",
    "item": "5",
    "subitem": "3",
    "desdobro": "1",
    "description": "Laboratórios de análise na área veterinária."
  },
  {
    "code": "050401",
    "item": "5",
    "subitem": "4",
    "desdobro": "1",
    "description": "Inseminação artificial, fertilização in vitro e congêneres."
  },
  {
    "code": "050501",
    "item": "5",
    "subitem": "5",
    "desdobro": "1",
    "description": "Bancos de sangue e de órgãos e congêneres."
  },
  {
    "code": "050601",
    "item": "5",
    "subitem": "6",
    "desdobro": "1",
    "description": "Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie."
  },
  {
    "code": "050701",
    "item": "5",
    "subitem": "7",
    "desdobro": "1",
    "description": "Unidade de atendimento, assistência ou tratamento móvel e congêneres."
  },
  {
    "code": "050801",
    "item": "5",
    "subitem": "8",
    "desdobro": "1",
    "description": "Guarda, tratamento, amestramento, embelezamento, alojamento e congêneres."
  },
  {
    "code": "050901",
    "item": "5",
    "subitem": "9",
    "desdobro": "1",
    "description": "Planos de atendimento e assistência médico-veterinária."
  },
  {
    "code": "060101",
    "item": "6",
    "subitem": "1",
    "desdobro": "1",
    "description": "Barbearia, cabeleireiros, manicuros, pedicuros e congêneres."
  },
  {
    "code": "060201",
    "item": "6",
    "subitem": "2",
    "desdobro": "1",
    "description": "Esteticistas, tratamento de pele, depilação e congêneres."
  },
  {
    "code": "060301",
    "item": "6",
    "subitem": "3",
    "desdobro": "1",
    "description": "Banhos, duchas, sauna, massagens e congêneres."
  },
  {
    "code": "060401",
    "item": "6",
    "subitem": "4",
    "desdobro": "1",
    "description": "Ginástica, dança, esportes, natação, artes marciais e demais atividades físicas."
  },
  {
    "code": "060501",
    "item": "6",
    "subitem": "5",
    "desdobro": "1",
    "description": "Centros de emagrecimento, spa e congêneres."
  },
  {
    "code": "060601",
    "item": "6",
    "subitem": "6",
    "desdobro": "1",
    "description": "Aplicação de tatuagens, piercings e congêneres."
  },
  {
    "code": "070101",
    "item": "7",
    "subitem": "1",
    "desdobro": "1",
    "description": "Engenharia e congêneres."
  },
  {
    "code": "070102",
    "item": "7",
    "subitem": "1",
    "desdobro": "2",
    "description": "Agronomia e congêneres."
  },
  {
    "code": "070103",
    "item": "7",
    "subitem": "1",
    "desdobro": "3",
    "description": "Agrimensura e congêneres."
  },
  {
    "code": "070104",
    "item": "7",
    "subitem": "1",
    "desdobro": "4",
    "description": "Arquitetura, urbanismo e congêneres."
  },
  {
    "code": "070105",
    "item": "7",
    "subitem": "1",
    "desdobro": "5",
    "description": "Geologia e congêneres."
  },
  {
    "code": "070106",
    "item": "7",
    "subitem": "1",
    "desdobro": "6",
    "description": "Paisagismo e congêneres."
  },
  {
    "code": "070201",
    "item": "7",
    "subitem": "2",
    "desdobro": "1",
    "description": "Execução, por administração, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes, inclusive sondagem, perfuração de poços, escavação, drenagem e irrigação, terraplanagem, pavimentação, concretagem e a instalação e montagem de produtos, peças e equipamentos (exceto o fornecimento de mercadorias produzidas pelo prestador de serviços fora do local da prestação dos serviços, que fica sujeito ao ICMS)."
  },
  {
    "code": "070202",
    "item": "7",
    "subitem": "2",
    "desdobro": "2",
    "description": "Execução, por empreitada ou subempreitada, de obras de construção civil, hidráulica ou elétrica e de outras obras semelhantes, inclusive sondagem, perfuração de poços, escavação, drenagem e irrigação, terraplanagem, pavimentação, concretagem e a instalação e montagem de produtos, peças e equipamentos (exceto o fornecimento de mercadorias produzidas pelo prestador de serviços fora do local da prestação dos serviços, que fica sujeito ao ICMS)."
  },
  {
    "code": "070301",
    "item": "7",
    "subitem": "3",
    "desdobro": "1",
    "description": "Elaboração de planos diretores, estudos de viabilidade, estudos organizacionais e outros, relacionados com obras e serviços de engenharia."
  },
  {
    "code": "070302",
    "item": "7",
    "subitem": "3",
    "desdobro": "2",
    "description": "Elaboração de anteprojetos, projetos básicos e projetos executivos para trabalhos de engenharia."
  },
  {
    "code": "070401",
    "item": "7",
    "subitem": "4",
    "desdobro": "1",
    "description": "Demolição."
  },
  {
    "code": "070501",
    "item": "7",
    "subitem": "5",
    "desdobro": "1",
    "description": "Reparação, conservação e reforma de edifícios e congêneres (exceto o fornecimento de mercadorias produzidas pelo prestador dos serviços, fora do local da prestação dos serviços, que fica sujeito ao ICMS)."
  },
  {
    "code": "070502",
    "item": "7",
    "subitem": "5",
    "desdobro": "2",
    "description": "Reparação, conservação e reforma de estradas, pontes, portos e congêneres (exceto o fornecimento de mercadorias produzidas pelo prestador dos serviços, fora do local da prestação dos serviços, que fica sujeito ao ICMS)."
  },
  {
    "code": "070601",
    "item": "7",
    "subitem": "6",
    "desdobro": "1",
    "description": "Colocação e instalação de tapetes, carpetes, cortinas e congêneres, com material fornecido pelo tomador do serviço."
  },
  {
    "code": "070602",
    "item": "7",
    "subitem": "6",
    "desdobro": "2",
    "description": "Colocação e instalação de assoalhos, revestimentos de parede, vidros, divisórias, placas de gesso e congêneres, com material fornecido pelo tomador do serviço."
  },
  {
    "code": "070701",
    "item": "7",
    "subitem": "7",
    "desdobro": "1",
    "description": "Recuperação, raspagem, polimento e lustração de pisos e congêneres."
  },
  {
    "code": "070801",
    "item": "7",
    "subitem": "8",
    "desdobro": "1",
    "description": "Calafetação."
  },
  {
    "code": "070901",
    "item": "7",
    "subitem": "9",
    "desdobro": "1",
    "description": "Varrição, coleta e remoção de lixo, rejeitos e outros resíduos quaisquer."
  },
  {
    "code": "070902",
    "item": "7",
    "subitem": "9",
    "desdobro": "2",
    "description": "Incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e outros resíduos quaisquer."
  },
  {
    "code": "071001",
    "item": "7",
    "subitem": "10",
    "desdobro": "1",
    "description": "Limpeza, manutenção e conservação de vias e logradouros públicos, parques, jardins e congêneres."
  },
  {
    "code": "071002",
    "item": "7",
    "subitem": "10",
    "desdobro": "2",
    "description": "Limpeza, manutenção e conservação de imóveis, chaminés, piscinas e congêneres."
  },
  {
    "code": "071101",
    "item": "7",
    "subitem": "11",
    "desdobro": "1",
    "description": "Decoração."
  },
  {
    "code": "071102",
    "item": "7",
    "subitem": "11",
    "desdobro": "2",
    "description": "Jardinagem, inclusive corte e poda de árvores."
  },
  {
    "code": "071201",
    "item": "7",
    "subitem": "12",
    "desdobro": "1",
    "description": "Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos."
  },
  {
    "code": "071301",
    "item": "7",
    "subitem": "13",
    "desdobro": "1",
    "description": "Dedetização, desinfecção, desinsetização, imunização, higienização, desratização, pulverização e congêneres."
  },
  {
    "code": "071601",
    "item": "7",
    "subitem": "16",
    "desdobro": "1",
    "description": "Florestamento, reflorestamento, semeadura, adubação, reparação de solo, plantio, silagem, colheita, corte e descascamento de árvores, silvicultura, exploração florestal e dos serviços congêneres indissociáveis da formação, manutenção e colheita de florestas, para quaisquer fins e por quaisquer meios."
  },
  {
    "code": "071701",
    "item": "7",
    "subitem": "17",
    "desdobro": "1",
    "description": "Escoramento, contenção de encostas e serviços congêneres."
  },
  {
    "code": "071801",
    "item": "7",
    "subitem": "18",
    "desdobro": "1",
    "description": "Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres."
  },
  {
    "code": "071901",
    "item": "7",
    "subitem": "19",
    "desdobro": "1",
    "description": "Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo."
  },
  {
    "code": "072001",
    "item": "7",
    "subitem": "20",
    "desdobro": "1",
    "description": "Aerofotogrametria (inclusive interpretação), cartografia, mapeamento e congêneres."
  },
  {
    "code": "072002",
    "item": "7",
    "subitem": "20",
    "desdobro": "2",
    "description": "Levantamentos batimétricos, geográficos, geodésicos, geológicos, geofísicos e congêneres."
  },
  {
    "code": "072003",
    "item": "7",
    "subitem": "20",
    "desdobro": "3",
    "description": "Levantamentos topográficos e congêneres."
  },
  {
    "code": "072101",
    "item": "7",
    "subitem": "21",
    "desdobro": "1",
    "description": "Pesquisa, perfuração, cimentação, mergulho, perfilagem, concretação, testemunhagem, pescaria, estimulação e outros serviços relacionados com a exploração e explotação de petróleo, gás natural e de outros recursos minerais."
  },
  {
    "code": "072201",
    "item": "7",
    "subitem": "22",
    "desdobro": "1",
    "description": "Nucleação e bombardeamento de nuvens e congêneres."
  },
  {
    "code": "080101",
    "item": "8",
    "subitem": "1",
    "desdobro": "1",
    "description": "Ensino regular pré-escolar, fundamental e médio."
  },
  {
    "code": "080102",
    "item": "8",
    "subitem": "1",
    "desdobro": "2",
    "description": "Ensino regular superior."
  },
  {
    "code": "080201",
    "item": "8",
    "subitem": "2",
    "desdobro": "1",
    "description": "Instrução, treinamento, orientação pedagógica e educacional, avaliação de conhecimentos de qualquer natureza."
  },
  {
    "code": "090101",
    "item": "9",
    "subitem": "1",
    "desdobro": "1",
    "description": "Hospedagem em hotéis, hotelaria marítima e congêneres (o valor da alimentação e gorjeta, quando incluído no preço da diária, fica sujeito ao Imposto Sobre Serviços)."
  },
  {
    "code": "090102",
    "item": "9",
    "subitem": "1",
    "desdobro": "2",
    "description": "Hospedagem em pensões, albergues, pousadas, hospedarias, ocupação por temporada com fornecimento de serviços e congêneres (o valor da alimentação e gorjeta, quando incluído no preço da diária, fica sujeito ao Imposto Sobre Serviços)."
  },
  {
    "code": "090103",
    "item": "9",
    "subitem": "1",
    "desdobro": "3",
    "description": "Hospedagem em motéis e congêneres (o valor da alimentação e gorjeta, quando incluído no preço da diária, fica sujeito ao Imposto Sobre Serviços)."
  },
  {
    "code": "090104",
    "item": "9",
    "subitem": "1",
    "desdobro": "4",
    "description": "Hospedagem em apart-service condominiais, flat, apart-hotéis, hotéis residência, residence-service, suite service e congêneres (o valor da alimentação e gorjeta, quando incluído no preço da diária, fica sujeito ao Imposto Sobre Serviços)."
  },
  {
    "code": "090201",
    "item": "9",
    "subitem": "2",
    "desdobro": "1",
    "description": "Agenciamento e intermediação de programas de turismo, passeios, viagens, excursões, hospedagens e congêneres."
  },
  {
    "code": "090202",
    "item": "9",
    "subitem": "2",
    "desdobro": "2",
    "description": "Organização, promoção e execução de programas de turismo, passeios, viagens, excursões, hospedagens e congêneres."
  },
  {
    "code": "090301",
    "item": "9",
    "subitem": "3",
    "desdobro": "1",
    "description": "Guias de turismo."
  },
  {
    "code": "100101",
    "item": "10",
    "subitem": "1",
    "desdobro": "1",
    "description": "Agenciamento, corretagem ou intermediação de câmbio."
  },
  {
    "code": "100102",
    "item": "10",
    "subitem": "1",
    "desdobro": "2",
    "description": "Agenciamento, corretagem ou intermediação de seguros."
  },
  {
    "code": "100103",
    "item": "10",
    "subitem": "1",
    "desdobro": "3",
    "description": "Agenciamento, corretagem ou intermediação de cartões de crédito."
  },
  {
    "code": "100104",
    "item": "10",
    "subitem": "1",
    "desdobro": "4",
    "description": "Agenciamento, corretagem ou intermediação de planos de saúde."
  },
  {
    "code": "100105",
    "item": "10",
    "subitem": "1",
    "desdobro": "5",
    "description": "Agenciamento, corretagem ou intermediação de planos de previdência privada."
  },
  {
    "code": "100201",
    "item": "10",
    "subitem": "2",
    "desdobro": "1",
    "description": "Agenciamento, corretagem ou intermediação de títulos em geral e valores mobiliários."
  },
  {
    "code": "100202",
    "item": "10",
    "subitem": "2",
    "desdobro": "2",
    "description": "Agenciamento, corretagem ou intermediação de contratos quaisquer."
  },
  {
    "code": "100301",
    "item": "10",
    "subitem": "3",
    "desdobro": "1",
    "description": "Agenciamento, corretagem ou intermediação de direitos de propriedade industrial, artística ou literária."
  },
  {
    "code": "100401",
    "item": "10",
    "subitem": "4",
    "desdobro": "1",
    "description": "Agenciamento, corretagem ou intermediação de contratos de arrendamento mercantil (leasing)."
  },
  {
    "code": "100402",
    "item": "10",
    "subitem": "4",
    "desdobro": "2",
    "description": "Agenciamento, corretagem ou intermediação de contratos de franquia (franchising)."
  },
  {
    "code": "100403",
    "item": "10",
    "subitem": "4",
    "desdobro": "3",
    "description": "Agenciamento, corretagem ou intermediação de faturização (factoring)."
  },
  {
    "code": "100501",
    "item": "10",
    "subitem": "5",
    "desdobro": "1",
    "description": "Agenciamento, corretagem ou intermediação de bens móveis ou imóveis, não abrangidos em outros itens ou subitens, por quaisquer meios."
  },
  {
    "code": "100502",
    "item": "10",
    "subitem": "5",
    "desdobro": "2",
    "description": "Agenciamento, corretagem ou intermediação de bens móveis ou imóveis realizados no âmbito de Bolsas de Mercadorias e Futuros, por quaisquer meios."
  },
  {
    "code": "100601",
    "item": "10",
    "subitem": "6",
    "desdobro": "1",
    "description": "Agenciamento marítimo."
  },
  {
    "code": "100701",
    "item": "10",
    "subitem": "7",
    "desdobro": "1",
    "description": "Agenciamento de notícias."
  },
  {
    "code": "100801",
    "item": "10",
    "subitem": "8",
    "desdobro": "1",
    "description": "Agenciamento de publicidade e propaganda, inclusive o agenciamento de veiculação por quaisquer meios."
  },
  {
    "code": "100901",
    "item": "10",
    "subitem": "9",
    "desdobro": "1",
    "description": "Representação de qualquer natureza, inclusive comercial."
  },
  {
    "code": "101001",
    "item": "10",
    "subitem": "10",
    "desdobro": "1",
    "description": "Distribuição de bens de terceiros."
  },
  {
    "code": "110101",
    "item": "11",
    "subitem": "1",
    "desdobro": "1",
    "description": "Guarda e estacionamento de veículos terrestres automotores."
  },
  {
    "code": "110102",
    "item": "11",
    "subitem": "1",
    "desdobro": "2",
    "description": "Guarda e estacionamento de aeronaves e de embarcações."
  },
  {
    "code": "110201",
    "item": "11",
    "subitem": "2",
    "desdobro": "1",
    "description": "Vigilância, segurança ou monitoramento de bens, pessoas e semoventes."
  },
  {
    "code": "110301",
    "item": "11",
    "subitem": "3",
    "desdobro": "1",
    "description": "Escolta, inclusive de veículos e cargas."
  },
  {
    "code": "110401",
    "item": "11",
    "subitem": "4",
    "desdobro": "1",
    "description": "Armazenamento, depósito, guarda de bens de qualquer espécie."
  },
  {
    "code": "110402",
    "item": "11",
    "subitem": "4",
    "desdobro": "2",
    "description": "Carga, descarga, arrumação de bens de qualquer espécie."
  },
  {
    "code": "110501",
    "item": "11",
    "subitem": "5",
    "desdobro": "1",
    "description": "Serviços relacionados ao monitoramento e rastreamento a distância, em qualquer via ou local, de veículos, cargas, pessoas e semoventes em circulação ou movimento, realizados por meio de telefonia móvel, transmissão de satélites, rádio ou qualquer outro meio, inclusive pelas empresas de Tecnologia da Informação Veicular, independentemente de o prestador de serviços ser proprietário ou não da infraestrutura de telecomunicações que utiliza."
  },
  {
    "code": "120101",
    "item": "12",
    "subitem": "1",
    "desdobro": "1",
    "description": "Espetáculos teatrais."
  },
  {
    "code": "120201",
    "item": "12",
    "subitem": "2",
    "desdobro": "1",
    "description": "Exibições cinematográficas."
  },
  {
    "code": "120301",
    "item": "12",
    "subitem": "3",
    "desdobro": "1",
    "description": "Espetáculos circenses."
  },
  {
    "code": "120401",
    "item": "12",
    "subitem": "4",
    "desdobro": "1",
    "description": "Programas de auditório."
  },
  {
    "code": "120501",
    "item": "12",
    "subitem": "5",
    "desdobro": "1",
    "description": "Parques de diversões, centros de lazer e congêneres."
  },
  {
    "code": "120601",
    "item": "12",
    "subitem": "6",
    "desdobro": "1",
    "description": "Boates, taxi-dancing e congêneres."
  },
  {
    "code": "120701",
    "item": "12",
    "subitem": "7",
    "desdobro": "1",
    "description": "Shows, ballet, danças, desfiles, bailes, óperas, concertos, recitais, festivais e congêneres."
  },
  {
    "code": "120801",
    "item": "12",
    "subitem": "8",
    "desdobro": "1",
    "description": "Feiras, exposições, congressos e congêneres."
  },
  {
    "code": "120901",
    "item": "12",
    "subitem": "9",
    "desdobro": "1",
    "description": "Bilhares."
  },
  {
    "code": "120902",
    "item": "12",
    "subitem": "9",
    "desdobro": "2",
    "description": "Boliches."
  },
  {
    "code": "120903",
    "item": "12",
    "subitem": "9",
    "desdobro": "3",
    "description": "Diversões eletrônicas ou não."
  },
  {
    "code": "121001",
    "item": "12",
    "subitem": "10",
    "desdobro": "1",
    "description": "Corridas e competições de animais."
  },
  {
    "code": "121101",
    "item": "12",
    "subitem": "11",
    "desdobro": "1",
    "description": "Competições esportivas ou de destreza física ou intelectual, com ou sem a participação do espectador."
  },
  {
    "code": "121201",
    "item": "12",
    "subitem": "12",
    "desdobro": "1",
    "description": "Execução de música."
  },
  {
    "code": "121301",
    "item": "12",
    "subitem": "13",
    "desdobro": "1",
    "description": "Produção, mediante ou sem encomenda prévia, de eventos, espetáculos, entrevistas, shows, ballet, danças, desfiles, bailes, teatros, óperas, concertos, recitais, festivais e congêneres."
  },
  {
    "code": "121401",
    "item": "12",
    "subitem": "14",
    "desdobro": "1",
    "description": "Fornecimento de música para ambientes fechados ou não, mediante transmissão por qualquer processo."
  },
  {
    "code": "121501",
    "item": "12",
    "subitem": "15",
    "desdobro": "1",
    "description": "Desfiles de blocos carnavalescos ou folclóricos, trios elétricos e congêneres."
  },
  {
    "code": "121601",
    "item": "12",
    "subitem": "16",
    "desdobro": "1",
    "description": "Exibição de filmes, entrevistas, musicais, espetáculos, shows, concertos, desfiles, óperas, competições esportivas, de destreza intelectual ou congêneres."
  },
  {
    "code": "121701",
    "item": "12",
    "subitem": "17",
    "desdobro": "1",
    "description": "Recreação e animação, inclusive em festas e eventos de qualquer natureza."
  },
  {
    "code": "130201",
    "item": "13",
    "subitem": "2",
    "desdobro": "1",
    "description": "Fonografia ou gravação de sons, inclusive trucagem, dublagem, mixagem e congêneres."
  },
  {
    "code": "130301",
    "item": "13",
    "subitem": "3",
    "desdobro": "1",
    "description": "Fotografia e cinematografia, inclusive revelação, ampliação, cópia, reprodução, trucagem e congêneres."
  },
  {
    "code": "130401",
    "item": "13",
    "subitem": "4",
    "desdobro": "1",
    "description": "Reprografia, microfilmagem e digitalização."
  },
  {
    "code": "130501",
    "item": "13",
    "subitem": "5",
    "desdobro": "1",
    "description": "Composição gráfica, inclusive confecção de impressos gráficos, fotocomposição, clicheria, zincografia, litografia e fotolitografia, exceto se destinados a posterior operação de comercialização ou industrialização, ainda que incorporados, de qualquer forma, a outra mercadoria que deva ser objeto de posterior circulação, tais como bulas, rótulos, etiquetas, caixas, cartuchos, embalagens e manuais técnicos e de instrução, quando ficarão sujeitos ao ICMS."
  },
  {
    "code": "140101",
    "item": "14",
    "subitem": "1",
    "desdobro": "1",
    "description": "Lubrificação, limpeza, lustração, revisão, carga e recarga, conserto, restauração, blindagem, manutenção e conservação de máquinas, veículos, aparelhos, equipamentos, motores, elevadores ou de qualquer objeto (exceto peças e partes empregadas, que ficam sujeitas ao ICMS)."
  },
  {
    "code": "140201",
    "item": "14",
    "subitem": "2",
    "desdobro": "1",
    "description": "Assistência técnica."
  },
  {
    "code": "140301",
    "item": "14",
    "subitem": "3",
    "desdobro": "1",
    "description": "Recondicionamento de motores (exceto peças e partes empregadas, que ficam sujeitas ao ICMS)."
  },
  {
    "code": "140401",
    "item": "14",
    "subitem": "4",
    "desdobro": "1",
    "description": "Recauchutagem ou regeneração de pneus."
  },
  {
    "code": "140501",
    "item": "14",
    "subitem": "5",
    "desdobro": "1",
    "description": "Restauração, recondicionamento, acondicionamento, pintura, beneficiamento, lavagem, secagem, tingimento, galvanoplastia, anodização, corte, recorte, plastificação, costura, acabamento, polimento e congêneres de objetos quaisquer."
  },
  {
    "code": "140601",
    "item": "14",
    "subitem": "6",
    "desdobro": "1",
    "description": "Instalação e montagem de aparelhos, máquinas e equipamentos, inclusive montagem industrial, prestados ao usuário final, exclusivamente com material por ele fornecido."
  },
  {
    "code": "140701",
    "item": "14",
    "subitem": "7",
    "desdobro": "1",
    "description": "Colocação de molduras e congêneres."
  },
  {
    "code": "140801",
    "item": "14",
    "subitem": "8",
    "desdobro": "1",
    "description": "Encadernação, gravação e douração de livros, revistas e congêneres."
  },
  {
    "code": "140901",
    "item": "14",
    "subitem": "9",
    "desdobro": "1",
    "description": "Alfaiataria e costura, quando o material for fornecido pelo usuário final, exceto aviamento."
  },
  {
    "code": "141001",
    "item": "14",
    "subitem": "10",
    "desdobro": "1",
    "description": "Tinturaria e lavanderia."
  },
  {
    "code": "141101",
    "item": "14",
    "subitem": "11",
    "desdobro": "1",
    "description": "Tapeçaria e reforma de estofamentos em geral."
  },
  {
    "code": "141201",
    "item": "14",
    "subitem": "12",
    "desdobro": "1",
    "description": "Funilaria e lanternagem."
  },
  {
    "code": "141301",
    "item": "14",
    "subitem": "13",
    "desdobro": "1",
    "description": "Carpintaria."
  },
  {
    "code": "141302",
    "item": "14",
    "subitem": "13",
    "desdobro": "2",
    "description": "Serralheria."
  },
  {
    "code": "141401",
    "item": "14",
    "subitem": "14",
    "desdobro": "1",
    "description": "Guincho intramunicipal."
  },
  {
    "code": "141402",
    "item": "14",
    "subitem": "14",
    "desdobro": "2",
    "description": "Guindaste e içamento."
  },
  {
    "code": "141403",
    "item": "14",
    "subitem": "14",
    "desdobro": "3",
    "description": "Guincho intramunicipal em construção civil."
  },
  {
    "code": "141404",
    "item": "14",
    "subitem": "14",
    "desdobro": "4",
    "description": "Guindaste e içamento em construção civil."
  },
  {
    "code": "150101",
    "item": "15",
    "subitem": "1",
    "desdobro": "1",
    "description": "Administração de fundos quaisquer e congêneres."
  },
  {
    "code": "150102",
    "item": "15",
    "subitem": "1",
    "desdobro": "2",
    "description": "Administração de consórcio e congêneres."
  },
  {
    "code": "150103",
    "item": "15",
    "subitem": "1",
    "desdobro": "3",
    "description": "Administração de cartão de crédito ou débito e congêneres."
  },
  {
    "code": "150104",
    "item": "15",
    "subitem": "1",
    "desdobro": "4",
    "description": "Administração de carteira de clientes e congêneres."
  },
  {
    "code": "150105",
    "item": "15",
    "subitem": "1",
    "desdobro": "5",
    "description": "Administração de cheques pré-datados e congêneres."
  },
  {
    "code": "150201",
    "item": "15",
    "subitem": "2",
    "desdobro": "1",
    "description": "Abertura de conta-corrente no País, bem como a manutenção da referida conta ativa e inativa."
  },
  {
    "code": "150202",
    "item": "15",
    "subitem": "2",
    "desdobro": "2",
    "description": "Abertura de conta-corrente no exterior, bem como a manutenção da referida conta ativa e inativa."
  },
  {
    "code": "150203",
    "item": "15",
    "subitem": "2",
    "desdobro": "3",
    "description": "Abertura de conta de investimentos e aplicação no País, bem como a manutenção da referida conta ativa e inativa."
  },
  {
    "code": "150204",
    "item": "15",
    "subitem": "2",
    "desdobro": "4",
    "description": "Abertura de conta de investimentos e aplicação no exterior, bem como a manutenção da referida conta ativa e inativa."
  },
  {
    "code": "150205",
    "item": "15",
    "subitem": "2",
    "desdobro": "5",
    "description": "Abertura de caderneta de poupança no País, bem como a manutenção da referida conta ativa e inativa."
  },
  {
    "code": "150206",
    "item": "15",
    "subitem": "2",
    "desdobro": "6",
    "description": "Abertura de caderneta de poupança no exterior, bem como a manutenção da referida conta ativa e inativa."
  },
  {
    "code": "150207",
    "item": "15",
    "subitem": "2",
    "desdobro": "7",
    "description": "Abertura de contas em geral no País, não abrangida em outro subitem, bem como a manutenção das referidas contas ativas e inativas."
  },
  {
    "code": "150208",
    "item": "15",
    "subitem": "2",
    "desdobro": "8",
    "description": "Abertura de contas em geral no exterior, não abrangida em outro subitem, bem como a manutenção das referidas contas ativas e inativas."
  },
  {
    "code": "150301",
    "item": "15",
    "subitem": "3",
    "desdobro": "1",
    "description": "Locação de cofres particulares."
  },
  {
    "code": "150302",
    "item": "15",
    "subitem": "3",
    "desdobro": "2",
    "description": "Manutenção de cofres particulares."
  },
  {
    "code": "150303",
    "item": "15",
    "subitem": "3",
    "desdobro": "3",
    "description": "Locação de terminais eletrônicos."
  },
  {
    "code": "150304",
    "item": "15",
    "subitem": "3",
    "desdobro": "4",
    "description": "Manutenção de terminais eletrônicos."
  },
  {
    "code": "150305",
    "item": "15",
    "subitem": "3",
    "desdobro": "5",
    "description": "Locação de terminais de atendimento."
  },
  {
    "code": "150306",
    "item": "15",
    "subitem": "3",
    "desdobro": "6",
    "description": "Manutenção de terminais de atendimento."
  },
  {
    "code": "150307",
    "item": "15",
    "subitem": "3",
    "desdobro": "7",
    "description": "Locação de bens e equipamentos em geral."
  },
  {
    "code": "150308",
    "item": "15",
    "subitem": "3",
    "desdobro": "8",
    "description": "Manutenção de bens e equipamentos em geral."
  },
  {
    "code": "150401",
    "item": "15",
    "subitem": "4",
    "desdobro": "1",
    "description": "Fornecimento ou emissão de atestados em geral, inclusive atestado de idoneidade, atestado de capacidade financeira e congêneres."
  },
  {
    "code": "150501",
    "item": "15",
    "subitem": "5",
    "desdobro": "1",
    "description": "Cadastro, elaboração de ficha cadastral, renovação cadastral e congêneres."
  },
  {
    "code": "150502",
    "item": "15",
    "subitem": "5",
    "desdobro": "2",
    "description": "Inclusão no Cadastro de Emitentes de Cheques sem Fundos - CCF."
  },
  {
    "code": "150503",
    "item": "15",
    "subitem": "5",
    "desdobro": "3",
    "description": "Exclusão no Cadastro de Emitentes de Cheques sem Fundos - CCF."
  },
  {
    "code": "150504",
    "item": "15",
    "subitem": "5",
    "desdobro": "4",
    "description": "Inclusão em quaisquer outros bancos cadastrais."
  },
  {
    "code": "150505",
    "item": "15",
    "subitem": "5",
    "desdobro": "5",
    "description": "Exclusão em quaisquer outros bancos cadastrais."
  },
  {
    "code": "150601",
    "item": "15",
    "subitem": "6",
    "desdobro": "1",
    "description": "Emissão, reemissão e fornecimento de avisos, comprovantes e documentos em geral"
  },
  {
    "code": "150602",
    "item": "15",
    "subitem": "6",
    "desdobro": "2",
    "description": "Abono de firmas."
  },
  {
    "code": "150603",
    "item": "15",
    "subitem": "6",
    "desdobro": "3",
    "description": "Coleta e entrega de documentos, bens e valores."
  },
  {
    "code": "150604",
    "item": "15",
    "subitem": "6",
    "desdobro": "4",
    "description": "Comunicação com outra agência ou com a administração central."
  },
  {
    "code": "150605",
    "item": "15",
    "subitem": "6",
    "desdobro": "5",
    "description": "Licenciamento eletrônico de veículos."
  },
  {
    "code": "150606",
    "item": "15",
    "subitem": "6",
    "desdobro": "6",
    "description": "Transferência de veículos."
  },
  {
    "code": "150607",
    "item": "15",
    "subitem": "6",
    "desdobro": "7",
    "description": "Agenciamento fiduciário ou depositário."
  },
  {
    "code": "150608",
    "item": "15",
    "subitem": "6",
    "desdobro": "8",
    "description": "Devolução de bens em custódia."
  },
  {
    "code": "150701",
    "item": "15",
    "subitem": "7",
    "desdobro": "1",
    "description": "Acesso, movimentação, atendimento e consulta a contas em geral, por qualquer meio ou processo, inclusive por telefone, fac-símile, internet e telex."
  },
  {
    "code": "150702",
    "item": "15",
    "subitem": "7",
    "desdobro": "2",
    "description": "Acesso a terminais de atendimento, inclusive vinte e quatro horas."
  },
  {
    "code": "150703",
    "item": "15",
    "subitem": "7",
    "desdobro": "3",
    "description": "Acesso a outro banco e à rede compartilhada."
  },
  {
    "code": "150704",
    "item": "15",
    "subitem": "7",
    "desdobro": "4",
    "description": "Fornecimento de saldo, extrato e demais informações relativas a contas em geral, por qualquer meio ou processo."
  },
  {
    "code": "150801",
    "item": "15",
    "subitem": "8",
    "desdobro": "1",
    "description": "Emissão, reemissão, alteração, cessão, substituição, cancelamento e registro de contrato de crédito."
  },
  {
    "code": "150802",
    "item": "15",
    "subitem": "8",
    "desdobro": "2",
    "description": "Estudo, análise e avaliação de operações de crédito."
  },
  {
    "code": "150803",
    "item": "15",
    "subitem": "8",
    "desdobro": "3",
    "description": "Emissão, concessão, alteração ou contratação de aval, fiança, anuência e congêneres."
  },
  {
    "code": "150804",
    "item": "15",
    "subitem": "8",
    "desdobro": "4",
    "description": "Serviços relativos à abertura de crédito, para quaisquer fins."
  },
  {
    "code": "150901",
    "item": "15",
    "subitem": "9",
    "desdobro": "1",
    "description": "Arrendamento mercantil (leasing) de quaisquer bens, inclusive cessão de direitos e obrigações, substituição de garantia, alteração, cancelamento e registro de contrato, e demais serviços relacionados ao arrendamento mercantil (leasing)."
  },
  {
    "code": "151001",
    "item": "15",
    "subitem": "10",
    "desdobro": "1",
    "description": "Serviços relacionados a cobranças em geral, de títulos quaisquer, de contas ou carnês, de câmbio, de tributos e por conta de terceiros, inclusive os efetuados por meio eletrônico, automático ou por máquinas de atendimento."
  },
  {
    "code": "151002",
    "item": "15",
    "subitem": "10",
    "desdobro": "2",
    "description": "Serviços relacionados a recebimentos em geral, de títulos quaisquer, de contas ou carnês, de câmbio, de tributos e por conta de terceiros, inclusive os efetuados por meio eletrônico, automático ou por máquinas de atendimento."
  },
  {
    "code": "151003",
    "item": "15",
    "subitem": "10",
    "desdobro": "3",
    "description": "Serviços relacionados a pagamentos em geral, de títulos quaisquer, de contas ou carnês, de câmbio, de tributos e por conta de terceiros, inclusive os efetuados por meio eletrônico, automático ou por máquinas de atendimento."
  },
  {
    "code": "151004",
    "item": "15",
    "subitem": "10",
    "desdobro": "4",
    "description": "Serviços relacionados a fornecimento de posição de cobrança, recebimento ou pagamento."
  },
  {
    "code": "151005",
    "item": "15",
    "subitem": "10",
    "desdobro": "5",
    "description": "Serviços relacionados a emissão de carnês, fichas de compensação, impressos e documentos em geral."
  },
  {
    "code": "151101",
    "item": "15",
    "subitem": "11",
    "desdobro": "1",
    "description": "Devolução de títulos, protesto de títulos, sustação de protesto, manutenção de títulos, reapresentação de títulos, e demais serviços a eles relacionados."
  },
  {
    "code": "151201",
    "item": "15",
    "subitem": "12",
    "desdobro": "1",
    "description": "Custódia em geral, inclusive de títulos e valores mobiliários."
  },
  {
    "code": "151301",
    "item": "15",
    "subitem": "13",
    "desdobro": "1",
    "description": "Serviços relacionados a operações de câmbio em geral, edição, alteração, prorrogação, cancelamento e baixa de contrato de câmbio."
  },
  {
    "code": "151302",
    "item": "15",
    "subitem": "13",
    "desdobro": "2",
    "description": "Serviços relacionados a emissão de registro de exportação ou de crédito."
  },
  {
    "code": "151303",
    "item": "15",
    "subitem": "13",
    "desdobro": "3",
    "description": "Serviços relacionados a cobrança ou depósito no exterior."
  },
  {
    "code": "151304",
    "item": "15",
    "subitem": "13",
    "desdobro": "4",
    "description": "Serviços relacionados a emissão, fornecimento e cancelamento de cheques de viagem."
  },
  {
    "code": "151305",
    "item": "15",
    "subitem": "13",
    "desdobro": "5",
    "description": "Serviços relacionados a fornecimento, transferência, cancelamento e demais serviços relativos a carta de crédito de importação, exportação e garantias recebidas."
  },
  {
    "code": "151306",
    "item": "15",
    "subitem": "13",
    "desdobro": "6",
    "description": "Serviços relacionados a envio e recebimento de mensagens em geral relacionadas a operações de câmbio."
  },
  {
    "code": "151401",
    "item": "15",
    "subitem": "14",
    "desdobro": "1",
    "description": "Fornecimento, emissão, reemissão de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres."
  },
  {
    "code": "151402",
    "item": "15",
    "subitem": "14",
    "desdobro": "2",
    "description": "Renovação de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres."
  },
  {
    "code": "151403",
    "item": "15",
    "subitem": "14",
    "desdobro": "3",
    "description": "Manutenção de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres."
  },
  {
    "code": "151501",
    "item": "15",
    "subitem": "15",
    "desdobro": "1",
    "description": "Compensação de cheques e títulos quaisquer."
  },
  {
    "code": "151502",
    "item": "15",
    "subitem": "15",
    "desdobro": "2",
    "description": "Serviços relacionados a depósito, inclusive depósito identificado, a saque de contas quaisquer, por qualquer meio ou processo, inclusive em terminais eletrônicos e de atendimento."
  },
  {
    "code": "151601",
    "item": "15",
    "subitem": "16",
    "desdobro": "1",
    "description": "Emissão, reemissão, liquidação, alteração, cancelamento e baixa de ordens de pagamento, ordens de crédito e similares, por qualquer meio ou processo."
  },
  {
    "code": "151602",
    "item": "15",
    "subitem": "16",
    "desdobro": "2",
    "description": "Serviços relacionados à transferência de valores, dados, fundos, pagamentos e similares, inclusive entre contas em geral."
  },
  {
    "code": "151701",
    "item": "15",
    "subitem": "17",
    "desdobro": "1",
    "description": "Emissão e fornecimento de cheques quaisquer, avulso ou por talão."
  },
  {
    "code": "151702",
    "item": "15",
    "subitem": "17",
    "desdobro": "2",
    "description": "Devolução de cheques quaisquer, avulso ou por talão."
  },
  {
    "code": "151703",
    "item": "15",
    "subitem": "17",
    "desdobro": "3",
    "description": "Sustação, cancelamento e oposição de cheques quaisquer, avulso ou por talão."
  },
  {
    "code": "151801",
    "item": "15",
    "subitem": "18",
    "desdobro": "1",
    "description": "Serviços relacionados a crédito imobiliário, de avaliação e vistoria de imóvel ou obra."
  },
  {
    "code": "151802",
    "item": "15",
    "subitem": "18",
    "desdobro": "2",
    "description": "Serviços relacionados a crédito imobiliário, de análise técnica e jurídica."
  },
  {
    "code": "151803",
    "item": "15",
    "subitem": "18",
    "desdobro": "3",
    "description": "Serviços relacionados a crédito imobiliário, de emissão, reemissão, alteração, transferência e renegociação de contrato."
  },
  {
    "code": "151804",
    "item": "15",
    "subitem": "18",
    "desdobro": "4",
    "description": "Serviços relacionados a crédito imobiliário, de emissão e reemissão do termo de quitação."
  },
  {
    "code": "151805",
    "item": "15",
    "subitem": "18",
    "desdobro": "5",
    "description": "Demais serviços relacionados a crédito imobiliário."
  },
  {
    "code": "160101",
    "item": "16",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de transporte coletivo municipal rodoviário de passageiros."
  },
  {
    "code": "160102",
    "item": "16",
    "subitem": "1",
    "desdobro": "2",
    "description": "Serviços de transporte coletivo municipal metroviário de passageiros."
  },
  {
    "code": "160103",
    "item": "16",
    "subitem": "1",
    "desdobro": "3",
    "description": "Serviços de transporte coletivo municipal ferroviário de passageiros."
  },
  {
    "code": "160104",
    "item": "16",
    "subitem": "1",
    "desdobro": "4",
    "description": "Serviços de transporte coletivo municipal aquaviário de passageiros."
  },
  {
    "code": "160201",
    "item": "16",
    "subitem": "2",
    "desdobro": "1",
    "description": "Outros serviços de transporte de natureza municipal."
  },
  {
    "code": "170101",
    "item": "17",
    "subitem": "1",
    "desdobro": "1",
    "description": "Assessoria ou consultoria de qualquer natureza, não contida em outros itens desta lista."
  },
  {
    "code": "170102",
    "item": "17",
    "subitem": "1",
    "desdobro": "2",
    "description": "Análise, exame, pesquisa, coleta, compilação e fornecimento de dados e informações de qualquer natureza, inclusive cadastro e similares."
  },
  {
    "code": "170201",
    "item": "17",
    "subitem": "2",
    "desdobro": "1",
    "description": "Datilografia, digitação, estenografia e congêneres."
  },
  {
    "code": "170202",
    "item": "17",
    "subitem": "2",
    "desdobro": "2",
    "description": "Expediente, secretaria em geral, apoio e infra-estrutura administrativa e congêneres."
  },
  {
    "code": "170203",
    "item": "17",
    "subitem": "2",
    "desdobro": "3",
    "description": "Resposta audível e congêneres."
  },
  {
    "code": "170204",
    "item": "17",
    "subitem": "2",
    "desdobro": "4",
    "description": "Redação, edição, revisão e congêneres."
  },
  {
    "code": "170205",
    "item": "17",
    "subitem": "2",
    "desdobro": "5",
    "description": "Interpretação, tradução e congêneres."
  },
  {
    "code": "170301",
    "item": "17",
    "subitem": "3",
    "desdobro": "1",
    "description": "Planejamento, coordenação, programação ou organização técnica."
  },
  {
    "code": "170302",
    "item": "17",
    "subitem": "3",
    "desdobro": "2",
    "description": "Planejamento, coordenação, programação ou organização financeira."
  },
  {
    "code": "170303",
    "item": "17",
    "subitem": "3",
    "desdobro": "3",
    "description": "Planejamento, coordenação, programação ou organização administrativa."
  },
  {
    "code": "170401",
    "item": "17",
    "subitem": "4",
    "desdobro": "1",
    "description": "Recrutamento, agenciamento, seleção e colocação de mão-de-obra."
  },
  {
    "code": "170501",
    "item": "17",
    "subitem": "5",
    "desdobro": "1",
    "description": "Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos ou temporários, contratados pelo prestador de serviço."
  },
  {
    "code": "170601",
    "item": "17",
    "subitem": "6",
    "desdobro": "1",
    "description": "Propaganda e publicidade, inclusive promoção de vendas, planejamento de campanhas ou sistemas de publicidade, elaboração de desenhos, textos e demais materiais publicitários."
  },
  {
    "code": "170801",
    "item": "17",
    "subitem": "8",
    "desdobro": "1",
    "description": "Franquia (franchising)."
  },
  {
    "code": "170901",
    "item": "17",
    "subitem": "9",
    "desdobro": "1",
    "description": "Perícias, laudos, exames técnicos e análises técnicas."
  },
  {
    "code": "171001",
    "item": "17",
    "subitem": "10",
    "desdobro": "1",
    "description": "Planejamento, organização e administração de feiras, exposições, e congêneres."
  },
  {
    "code": "171002",
    "item": "17",
    "subitem": "10",
    "desdobro": "2",
    "description": "Planejamento, organização e administração de congressos e congêneres."
  },
  {
    "code": "171101",
    "item": "17",
    "subitem": "11",
    "desdobro": "1",
    "description": "Organização de festas e recepções."
  },
  {
    "code": "171102",
    "item": "17",
    "subitem": "11",
    "desdobro": "2",
    "description": "Bufê (exceto o fornecimento de alimentação e bebidas, que fica sujeito ao ICMS)."
  },
  {
    "code": "171201",
    "item": "17",
    "subitem": "12",
    "desdobro": "1",
    "description": "Administração em geral, inclusive de bens e negócios de terceiros."
  },
  {
    "code": "171301",
    "item": "17",
    "subitem": "13",
    "desdobro": "1",
    "description": "Leilão e congêneres."
  },
  {
    "code": "171401",
    "item": "17",
    "subitem": "14",
    "desdobro": "1",
    "description": "Advocacia"
  },
  {
    "code": "171501",
    "item": "17",
    "subitem": "15",
    "desdobro": "1",
    "description": "Arbitragem de qualquer espécie, inclusive jurídica."
  },
  {
    "code": "171601",
    "item": "17",
    "subitem": "16",
    "desdobro": "1",
    "description": "Auditoria."
  },
  {
    "code": "171701",
    "item": "17",
    "subitem": "17",
    "desdobro": "1",
    "description": "Análise de Organização e Métodos."
  },
  {
    "code": "171801",
    "item": "17",
    "subitem": "18",
    "desdobro": "1",
    "description": "Atuária e cálculos técnicos de qualquer natureza."
  },
  {
    "code": "171901",
    "item": "17",
    "subitem": "19",
    "desdobro": "1",
    "description": "Contabilidade, inclusive serviços técnicos e auxiliares."
  },
  {
    "code": "172001",
    "item": "17",
    "subitem": "20",
    "desdobro": "1",
    "description": "Consultoria e assessoria econômica ou financeira."
  },
  {
    "code": "172101",
    "item": "17",
    "subitem": "21",
    "desdobro": "1",
    "description": "Estatística."
  },
  {
    "code": "172201",
    "item": "17",
    "subitem": "22",
    "desdobro": "1",
    "description": "Cobrança em geral."
  },
  {
    "code": "172301",
    "item": "17",
    "subitem": "23",
    "desdobro": "1",
    "description": "Assessoria, análise, avaliação, atendimento, consulta, cadastro, seleção, gerenciamento de informações, administração de contas a receber ou a pagar e em geral, relacionados a operações de faturização (factoring)."
  },
  {
    "code": "172401",
    "item": "17",
    "subitem": "24",
    "desdobro": "1",
    "description": "Apresentação de palestras, conferências, seminários e congêneres."
  },
  {
    "code": "172501",
    "item": "17",
    "subitem": "25",
    "desdobro": "1",
    "description": "Inserção de textos, desenhos e outros materiais de propaganda e publicidade, em qualquer meio (exceto em livros, jornais, periódicos e nas modalidades de serviços de radiodifusão sonora e de sons e imagens de recepção livre e gratuita)."
  },
  {
    "code": "180101",
    "item": "18",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de regulação de sinistros vinculados a contratos de seguros e congêneres."
  },
  {
    "code": "180102",
    "item": "18",
    "subitem": "1",
    "desdobro": "2",
    "description": "Serviços de inspeção e avaliação de riscos para cobertura de contratos de seguros e congêneres."
  },
  {
    "code": "180103",
    "item": "18",
    "subitem": "1",
    "desdobro": "3",
    "description": "Serviços de prevenção e gerência de riscos seguráveis e congêneres."
  },
  {
    "code": "190101",
    "item": "19",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de distribuição e venda de bilhetes e demais produtos de loteria, cartões, pules ou cupons de apostas, sorteios, prêmios, inclusive os decorrentes de títulos de capitalização e congêneres."
  },
  {
    "code": "190102",
    "item": "19",
    "subitem": "1",
    "desdobro": "2",
    "description": "Serviços de distribuição e venda de bingos e congêneres."
  },
  {
    "code": "200101",
    "item": "20",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços portuários, ferroportuários, utilização de porto, movimentação de passageiros, reboque de embarcações, rebocador escoteiro, atracação, desatracação, serviços de praticagem, capatazia, armazenagem de qualquer natureza, serviços acessórios, movimentação de mercadorias, serviços de apoio marítimo, de movimentação ao largo, serviços de armadores, estiva, conferência, logística e congêneres. (prestado em terra)"
  },
  {
    "code": "200102",
    "item": "20",
    "subitem": "1",
    "desdobro": "2",
    "description": "Serviços portuários, ferroportuários, utilização de porto, movimentação de passageiros, reboque de embarcações, rebocador escoteiro, atracação, desatracação, serviços de praticagem, capatazia, armazenagem de qualquer natureza, serviços acessórios, movimentação de mercadorias, serviços de apoio marítimo, de movimentação ao largo, serviços de armadores, estiva, conferência, logística e congêneres. (prestado em águas marinhas)"
  },
  {
    "code": "200201",
    "item": "20",
    "subitem": "2",
    "desdobro": "1",
    "description": "Serviços aeroportuários, utilização de aeroporto, movimentação de passageiros, armazenagem de qualquer natureza, capatazia, movimentação de aeronaves, serviços de apoio aeroportuários, serviços acessórios, movimentação de mercadorias, logística e congêneres."
  },
  {
    "code": "200301",
    "item": "20",
    "subitem": "3",
    "desdobro": "1",
    "description": "Serviços de terminais rodoviários, ferroviários, metroviários, movimentação de passageiros, mercadorias, inclusive suas operações, logística e congêneres."
  },
  {
    "code": "210101",
    "item": "21",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de registros públicos, cartorários e notariais."
  },
  {
    "code": "220101",
    "item": "22",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de exploração de rodovia mediante cobrança de preço ou pedágio dos usuários, envolvendo execução de serviços de conservação, manutenção, melhoramentos para adequação de capacidade e segurança de trânsito, operação, monitoração, assistência aos usuários e outros serviços definidos em contratos, atos de concessão ou de permissão ou em normas oficiais."
  },
  {
    "code": "230101",
    "item": "23",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de programação e comunicação visual e congêneres."
  },
  {
    "code": "230102",
    "item": "23",
    "subitem": "1",
    "desdobro": "2",
    "description": "Serviços de desenho industrial e congêneres."
  },
  {
    "code": "240101",
    "item": "24",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de chaveiros, confecção de carimbos e congêneres."
  },
  {
    "code": "240102",
    "item": "24",
    "subitem": "1",
    "desdobro": "2",
    "description": "Serviços de placas, sinalização visual, banners, adesivos e congêneres."
  },
  {
    "code": "250101",
    "item": "25",
    "subitem": "1",
    "desdobro": "1",
    "description": "Funerais, inclusive fornecimento de caixão, urna ou esquifes; aluguel de capela; transporte do corpo cadavérico; fornecimento de flores, coroas e outros paramentos; desembaraço de certidão de óbito; fornecimento de véu, essa e outros adornos; embalsamento, embelezamento, conservação ou restauração de cadáveres."
  },
  {
    "code": "250201",
    "item": "25",
    "subitem": "2",
    "desdobro": "1",
    "description": "Translado intramunicipal de corpos e partes de corpos cadavéricos."
  },
  {
    "code": "250202",
    "item": "25",
    "subitem": "2",
    "desdobro": "2",
    "description": "Cremação de corpos e partes de corpos cadavéricos."
  },
  {
    "code": "250301",
    "item": "25",
    "subitem": "3",
    "desdobro": "1",
    "description": "Planos ou convênio funerários."
  },
  {
    "code": "250401",
    "item": "25",
    "subitem": "4",
    "desdobro": "1",
    "description": "Manutenção e conservação de jazigos e cemitérios."
  },
  {
    "code": "250501",
    "item": "25",
    "subitem": "5",
    "desdobro": "1",
    "description": "Cessão de uso de espaços em cemitérios para sepultamento."
  },
  {
    "code": "260101",
    "item": "26",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores, inclusive pelos correios e suas agências franqueadas."
  },
  {
    "code": "260102",
    "item": "26",
    "subitem": "1",
    "desdobro": "2",
    "description": "Serviços de courrier e congêneres."
  },
  {
    "code": "270101",
    "item": "27",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de assistência social."
  },
  {
    "code": "280101",
    "item": "28",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de avaliação de bens e serviços de qualquer natureza."
  },
  {
    "code": "290101",
    "item": "29",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de biblioteconomia."
  },
  {
    "code": "300101",
    "item": "30",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de biologia e biotecnologia."
  },
  {
    "code": "300102",
    "item": "30",
    "subitem": "1",
    "desdobro": "2",
    "description": "Serviços de química."
  },
  {
    "code": "310101",
    "item": "31",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços técnicos em edificações e congêneres."
  },
  {
    "code": "310102",
    "item": "31",
    "subitem": "1",
    "desdobro": "2",
    "description": "Serviços técnicos em eletrônica, eletrotécnica e congêneres."
  },
  {
    "code": "310103",
    "item": "31",
    "subitem": "1",
    "desdobro": "3",
    "description": "Serviços técnicos em mecânica e congêneres."
  },
  {
    "code": "310104",
    "item": "31",
    "subitem": "1",
    "desdobro": "4",
    "description": "Serviços técnicos em telecomunicações e congêneres."
  },
  {
    "code": "320101",
    "item": "32",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de desenhos técnicos."
  },
  {
    "code": "330101",
    "item": "33",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres."
  },
  {
    "code": "340101",
    "item": "34",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de investigações particulares, detetives e congêneres."
  },
  {
    "code": "350101",
    "item": "35",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de reportagem e jornalismo."
  },
  {
    "code": "350102",
    "item": "35",
    "subitem": "1",
    "desdobro": "2",
    "description": "Serviços de assessoria de imprensa."
  },
  {
    "code": "350103",
    "item": "35",
    "subitem": "1",
    "desdobro": "3",
    "description": "Serviços de relações públicas."
  },
  {
    "code": "360101",
    "item": "36",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de meteorologia."
  },
  {
    "code": "370101",
    "item": "37",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de artistas, atletas, modelos e manequins."
  },
  {
    "code": "380101",
    "item": "38",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de museologia."
  },
  {
    "code": "390101",
    "item": "39",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços de ourivesaria e lapidação (quando o material for fornecido pelo tomador do serviço)."
  },
  {
    "code": "400101",
    "item": "40",
    "subitem": "1",
    "desdobro": "1",
    "description": "Obras de arte sob encomenda."
  },
  {
    "code": "990101",
    "item": "99",
    "subitem": "1",
    "desdobro": "1",
    "description": "Serviços sem a incidência de ISSQN e ICMS"
  }
] as const;
