// Code generated by go-dfe/nfse/tables/gen/generate.py. DO NOT EDIT.

export interface NfseMotiveOption { value: string; label: string }

export const NFSE_THIRD_PARTY_MOTIVES: readonly NfseMotiveOption[] = [
  {
    "value": "1",
    "label": "Importação de Serviço"
  },
  {
    "value": "2",
    "label": "Tomador/Intermediário obrigado a emitir NFS-e por legislação municipal"
  },
  {
    "value": "3",
    "label": "Tomador/Intermediário emitindo NFS-e por recusa de emissão pelo prestador"
  },
  {
    "value": "4",
    "label": "Tomador/Intermediário emitindo por rejeitar a NFS-e emitida pelo prestador"
  }
] as const;

export const NFSE_CANCELLATION_MOTIVES: readonly NfseMotiveOption[] = [
  {
    "value": "1",
    "label": "Erro na Emissão"
  },
  {
    "value": "2",
    "label": "Serviço não Prestado"
  },
  {
    "value": "9",
    "label": "Outros"
  }
] as const;

export const NFSE_FISCAL_ANALYSIS_MOTIVES: readonly NfseMotiveOption[] = [
  {
    "value": "1",
    "label": "Erro na Emissão"
  },
  {
    "value": "2",
    "label": "Serviço não Prestado"
  },
  {
    "value": "9",
    "label": "Outros"
  }
] as const;

export const NFSE_SUBSTITUTION_MOTIVES: readonly NfseMotiveOption[] = [
  {
    "value": "01",
    "label": "Desenquadramento de NFS-e do Simples Nacional"
  },
  {
    "value": "02",
    "label": "Enquadramento de NFS-e no Simples Nacional"
  },
  {
    "value": "03",
    "label": "Inclusão Retroativa de Imunidade/Isenção para NFS-e"
  },
  {
    "value": "04",
    "label": "Exclusão Retroativa de Imunidade/Isenção para NFS-e"
  },
  {
    "value": "05",
    "label": "Rejeição de NFS-e pelo tomador ou pelo intermediário se responsável pelo recolhimento do tributo"
  },
  {
    "value": "99",
    "label": "Outros"
  }
] as const;

export const NFSE_REJECTION_MOTIVES: readonly NfseMotiveOption[] = [
  {
    "value": "1",
    "label": "NFS-e em duplicidade"
  },
  {
    "value": "2",
    "label": "NFS-e já emitida pelo tomador"
  },
  {
    "value": "3",
    "label": "Não ocorrência do fato gerador"
  },
  {
    "value": "4",
    "label": "Erro quanto a responsabilidade tributária"
  },
  {
    "value": "5",
    "label": "Erro quanto ao valor do serviço, valor das deduções ou serviço prestado ou data do fato gerador"
  },
  {
    "value": "9",
    "label": "Outros"
  }
] as const;

