// Code generated by go-dfe/nfse/tables/gen/generate.py. DO NOT EDIT.

interface IndOpEntry {
  code: string;
  tipo_operacao: string;
  caracteristica_fornecimento: string;
  local_fornecimento: string;
  campo_leiaute: string;
}

export const NFSE_INDOP = [
  {
    "code": "020101",
    "tipo_operacao": "Operação com bem imóvel, bem imaterial, inclusive direito,  relacionada a bem imóvel",
    "caracteristica_fornecimento": "Execução de operações com bem imóvel, bem imaterial, inclusive direito, relacionado a bem imóvel",
    "local_fornecimento": "Localidade do imóvel (1)",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/serv/locPrest/cLocPrestacao"
  },
  {
    "code": "020201",
    "tipo_operacao": "Serviço prestado fisicamente sobre bem imóvel",
    "caracteristica_fornecimento": "Execução de serviços sobre bem imóvel",
    "local_fornecimento": "Localidade do imóvel (1)",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/serv/locPrest/cLocPrestacao"
  },
  {
    "code": "020301",
    "tipo_operacao": "Serviço de administração e intermediação de bem imóvel",
    "caracteristica_fornecimento": "Execução dos serviços de administração e intermediação de bens imóveis",
    "local_fornecimento": "Localidade do imóvel (1)",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/serv/locPrest/cLocPrestacao"
  },
  {
    "code": "030101",
    "tipo_operacao": "Serviço prestado fisicamente sobre a pessoa ou fruído presencialmente por pessoa física",
    "caracteristica_fornecimento": "Execução de serviços diversos exclusivamente prestados fisicamente sobre a pessoa ou integralmente fruídos presencialmente por pessoa física (2)",
    "local_fornecimento": "Estabelecimento do fornecedor",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/prest/end/"
  },
  {
    "code": "030102",
    "tipo_operacao": "Serviço prestado fisicamente sobre a pessoa ou fruído presencialmente por pessoa física",
    "caracteristica_fornecimento": "Execução de serviços diversos exclusivamente prestados fisicamente sobre a pessoa ou integralmente fruídos presencialmente por pessoa física (2)",
    "local_fornecimento": "Endereço do adquirente",
    "campo_leiaute": "-> Se NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 0–O destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador=adquirente=destinatário) NFSe/infNFSe/DPS/infDPS/toma/end -> SeNaoSe NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 1 – o destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador=adquirente≠destinatário); NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/"
  },
  {
    "code": "030103",
    "tipo_operacao": "Serviço prestado fisicamente sobre a pessoa ou fruído presencialmente por pessoa física",
    "caracteristica_fornecimento": "Execução de serviços diversos exclusivamente prestados fisicamente sobre a pessoa ou integralmente fruídos presencialmente por pessoa física (2)",
    "local_fornecimento": "Endereço do destinatário",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/"
  },
  {
    "code": "030104",
    "tipo_operacao": "Serviço prestado fisicamente sobre a pessoa ou fruído presencialmente por pessoa física",
    "caracteristica_fornecimento": "Execução de serviços diversos exclusivamente prestados fisicamente sobre a pessoa ou integralmente fruídos presencialmente por pessoa física (2)",
    "local_fornecimento": "Endereço diverso do fornecedor, adquirente ou destinatário",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/serv/locPrest/cLocPrestacao"
  },
  {
    "code": "040101",
    "tipo_operacao": "Serviço de planejamento, organização e administração de feiras, exposições, congressos, espetáculos, exibições e congêneres",
    "caracteristica_fornecimento": "Execução de serviços de planejamento, organização e administração de feiras, exposições, congressos, espetáculos, exibições e congêneres",
    "local_fornecimento": "Local do Evento",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/serv/atvEvento/"
  },
  {
    "code": "050101",
    "tipo_operacao": "Serviço prestado fisicamente sobre bem móvel material",
    "caracteristica_fornecimento": "Execução de serviços diversos fisicamente prestados sobre bem móvel material",
    "local_fornecimento": "Estabelecimento do fornecedor",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/prest/end/"
  },
  {
    "code": "050102",
    "tipo_operacao": "Serviço prestado fisicamente sobre bem móvel material",
    "caracteristica_fornecimento": "Execução de serviços diversos fisicamente prestados sobre bem móvel material",
    "local_fornecimento": "Endereço do adquirente",
    "campo_leiaute": "-> Se NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 0–O destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador=adquirente=destinatário) NFSe/infNFSe/DPS/infDPS/toma/end -> SeNaoSe NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 1 – o destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador=adquirente≠destinatário); NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/"
  },
  {
    "code": "050103",
    "tipo_operacao": "Serviço prestado fisicamente sobre bem móvel material",
    "caracteristica_fornecimento": "Execução de serviços diversos fisicamente prestados sobre bem móvel material",
    "local_fornecimento": "Endereço do destinatário",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/"
  },
  {
    "code": "050104",
    "tipo_operacao": "Serviço prestado fisicamente sobre bem móvel material",
    "caracteristica_fornecimento": "Execução de serviços diversos fisicamente prestados sobre bem móvel material",
    "local_fornecimento": "Endereço diverso do fornecedor, adquirente ou destinatário",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/serv/locPrest/cLocPrestacao"
  },
  {
    "code": "050201",
    "tipo_operacao": "Serviços portuários",
    "caracteristica_fornecimento": "Execução de serviços portuários",
    "local_fornecimento": "Local da prestação",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/serv/locPrest/cLocPrestacao"
  },
  {
    "code": "060101",
    "tipo_operacao": "Serviço de transporte de passageiros",
    "caracteristica_fornecimento": "Execução de serviços de transporte de passageiros",
    "local_fornecimento": "Local de início do transporte",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/serv/locPrest/cLocPrestacao"
  },
  {
    "code": "070101",
    "tipo_operacao": "Serviço de transporte de carga",
    "caracteristica_fornecimento": "Execução de serviços de transporte de carga",
    "local_fornecimento": "Endereço fornecido para entrega",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/serv/locPrest/cLocPrestacao"
  },
  {
    "code": "070102",
    "tipo_operacao": "Serviço de transporte de carga",
    "caracteristica_fornecimento": "Execução de serviços de transporte de carga",
    "local_fornecimento": "Local da retirada",
    "campo_leiaute": "NFSe/infNFSe/DPS/infDPS/serv/locPrest/cLocPrestacao"
  },
  {
    "code": "080101",
    "tipo_operacao": "Serviço de exploração de via",
    "caracteristica_fornecimento": "Execução de serviços de exploração de via",
    "local_fornecimento": "Local da prestação, correspondente à extensão da via explorada e proporcional ao território dos entes tributantes",
    "campo_leiaute": "EXCLUSIVO PARA NFS-e Via."
  },
  {
    "code": "100101",
    "tipo_operacao": "Cessão de espaço para prestação de serviços publicitários, em operações onerosas (4)",
    "caracteristica_fornecimento": "Execução de operações de cessão de espaço para prestação de serviços publicitários",
    "local_fornecimento": "Local do domicílio principal do adquirente (3)",
    "campo_leiaute": "-> Se NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 0–O destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador=adquirente=destinatário) NFSe/infNFSe/DPS/infDPS/toma/end -> SeNaoSe NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 1 – o destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador=adquirente≠destinatário); NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/"
  },
  {
    "code": "100102",
    "tipo_operacao": "Cessão de espaço para prestação de serviços publicitários, em operações onerosas (4)",
    "caracteristica_fornecimento": "Execução de operações de cessão de espaço para prestação de serviços publicitários",
    "local_fornecimento": "Local do domicílio do destinatário, nos casos de adquirente residente ou domiciliado no exterior (5)(6)",
    "campo_leiaute": "-> Se NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 0–O destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador=adquirente=destinatário) NFSe/infNFSe/DPS/infDPS/toma/end/endExt -> SeNaoSe NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 1 – o destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador=adquirente≠destinatário); NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/end/endExt"
  },
  {
    "code": "100201",
    "tipo_operacao": "Cessão de espaço para prestação de serviços publicitários, em operações não onerosas (4)",
    "caracteristica_fornecimento": "Execução de operações de cessão de espaço para prestação de serviços publicitários",
    "local_fornecimento": "Local do domicílio principal do destinatário (6)",
    "campo_leiaute": "-> Se NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 0–O destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador=adquirente=destinatário) NFSe/infNFSe/DPS/infDPS/toma/end -> SeNaoSe NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 1 – o destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador=adquirente≠destinatário); NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/"
  },
  {
    "code": "100301",
    "tipo_operacao": "Demais serviços, em operações onerosas",
    "caracteristica_fornecimento": "Execução dos demais serviços em operações não especificadas anteriormente ou, nos serviços de que trata o inc. III, estes sejam, ainda que parcialmente, prestados à distância (2)",
    "local_fornecimento": "Local do domicílio principal do adquirente (3)",
    "campo_leiaute": "-> Se NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 0–O destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador=adquirente=destinatário) NFSe/infNFSe/DPS/infDPS/toma/end -> SeNaoSe NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 1 – o destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador=adquirente≠destinatário); NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/"
  },
  {
    "code": "100302",
    "tipo_operacao": "Demais serviços, em operações onerosas",
    "caracteristica_fornecimento": "Execução dos demais serviços em operações não especificadas anteriormente ou, nos serviços de que trata o inc. III, estes sejam, ainda que parcialmente, prestados à distância (2)",
    "local_fornecimento": "Local do domicílio do destinatário, nos casos de adquirente residente ou domiciliado no exterior (5)(6)",
    "campo_leiaute": "-> Se NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 0–O destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador=adquirente=destinatário) NFSe/infNFSe/DPS/infDPS/toma/end -> SeNaoSe NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 1 – o destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador=adquirente≠destinatário); NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/"
  },
  {
    "code": "100401",
    "tipo_operacao": "Demais serviços, em operações não onerosas",
    "caracteristica_fornecimento": "Execução dos demais serviços em operações não especificadas anteriormente ou, nos serviços de que tratam o inc. III, estes sejam, ainda que parcialmente, prestados à distância",
    "local_fornecimento": "Local do domicílio principal do destinatário (6)",
    "campo_leiaute": "-> Se NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 0–O destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador=adquirente=destinatário) NFSe/infNFSe/DPS/infDPS/toma/end -> SeNaoSe NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 1 – o destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador=adquirente≠destinatário); NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/"
  },
  {
    "code": "100501",
    "tipo_operacao": "Demais bens móveis imateriais, inclusive direitos, em operações onerosas",
    "caracteristica_fornecimento": "Execução de demais operações não especificadas anteriormente com bens móveis imateriais, inclusive direitos",
    "local_fornecimento": "Local do domicílio principal do adquirente (3)",
    "campo_leiaute": "-> Se NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 0–O destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador=adquirente=destinatário) NFSe/infNFSe/DPS/infDPS/toma/ -> SeNaoSe NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 1 – o destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador=adquirente≠destinatário); NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/"
  },
  {
    "code": "100502",
    "tipo_operacao": "Demais bens móveis imateriais, inclusive direitos, em operações onerosas",
    "caracteristica_fornecimento": "Execução de demais operações não especificadas anteriormente com bens móveis imateriais, inclusive direitos",
    "local_fornecimento": "Local do domicílio do destinatário, nos casos de adquirente residente ou domiciliado no exterior (5)(6)",
    "campo_leiaute": "-> Se NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 0–O destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador=adquirente=destinatário) NFSe/infNFSe/DPS/infDPS/toma/end/endExt/ -> SeNaoSe NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 1 – o destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador=adquirente≠destinatário); NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/end/endExt/"
  },
  {
    "code": "100601",
    "tipo_operacao": "Demais bens móveis imateriais, inclusive direitos, em operações não onerosas",
    "caracteristica_fornecimento": "Execução de demais operações não especificadas anteriormente com bens móveis imateriais, inclusive direitos",
    "local_fornecimento": "Local do domicílio principal do destinatário (6)",
    "campo_leiaute": "-> Se NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 0–O destinatário é o próprio tomador/adquirente identificado na NFS-e (tomador=adquirente=destinatário) NFSe/infNFSe/DPS/infDPS/toma/end -> SeNaoSe NFSe/infNFSe/DPS/infDPS/IBSCBS/indDest = 1 – o destinatário não é o próprio adquirente, podendo ser outra pessoa, física ou jurídica (ou equiparada), ou um estabelecimento diferente do indicado como tomador (tomador=adquirente≠destinatário); NFSe/infNFSe/DPS/infDPS/IBSCBS/dest/"
  }
] as const;
