// Code generated by go-dfe/nfse/tables/gen/generate.py. DO NOT EDIT.

export interface NfseCountryEntry {
  code: string;
  name: string;
}

export const NFSE_COUNTRIES: readonly NfseCountryEntry[] = [
  {
    "code": "AD",
    "name": "Andorra"
  },
  {
    "code": "AE",
    "name": "Emirados Árabes Unidos"
  },
  {
    "code": "AF",
    "name": "Afeganistão"
  },
  {
    "code": "AG",
    "name": "Antígua e Barbuda"
  },
  {
    "code": "AI",
    "name": "Anguilla"
  },
  {
    "code": "AL",
    "name": "Albânia, República da"
  },
  {
    "code": "AM",
    "name": "Armênia, República da"
  },
  {
    "code": "AO",
    "name": "Angola"
  },
  {
    "code": "AQ",
    "name": "Antártica"
  },
  {
    "code": "AR",
    "name": "Argentina"
  },
  {
    "code": "AS",
    "name": "Samoa Americana"
  },
  {
    "code": "AT",
    "name": "Áustria"
  },
  {
    "code": "AU",
    "name": "Austrália"
  },
  {
    "code": "AW",
    "name": "Aruba"
  },
  {
    "code": "AX",
    "name": "Aland, Ilhas"
  },
  {
    "code": "AZ",
    "name": "Azerbaijão, República do"
  },
  {
    "code": "BA",
    "name": "Bosnia-Herzegovina, República da"
  },
  {
    "code": "BB",
    "name": "Barbados"
  },
  {
    "code": "BD",
    "name": "Bangladesh"
  },
  {
    "code": "BE",
    "name": "Bélgica"
  },
  {
    "code": "BF",
    "name": "Burkina Faso"
  },
  {
    "code": "BG",
    "name": "Bulgária, República da"
  },
  {
    "code": "BH",
    "name": "Bahrein, Ilhas"
  },
  {
    "code": "BI",
    "name": "Burundi"
  },
  {
    "code": "BJ",
    "name": "Benim"
  },
  {
    "code": "BL",
    "name": "São Bartolomeu"
  },
  {
    "code": "BM",
    "name": "Bermudas"
  },
  {
    "code": "BN",
    "name": "Brunei"
  },
  {
    "code": "BO",
    "name": "Bolívia"
  },
  {
    "code": "BQ",
    "name": "Bonaire, Santo Eustáquio e Saba"
  },
  {
    "code": "BR",
    "name": "Brasil"
  },
  {
    "code": "BS",
    "name": "Bahamas, Ilhas"
  },
  {
    "code": "BT",
    "name": "Butão"
  },
  {
    "code": "BV",
    "name": "Bouvet, Ilha"
  },
  {
    "code": "BW",
    "name": "Botsuana"
  },
  {
    "code": "BY",
    "name": "Belarus, República da"
  },
  {
    "code": "BZ",
    "name": "Belize"
  },
  {
    "code": "CA",
    "name": "Canadá"
  },
  {
    "code": "CC",
    "name": "Cocos(Keeling), Ilhas"
  },
  {
    "code": "CD",
    "name": "Congo, República Democrática do"
  },
  {
    "code": "CF",
    "name": "República Centro-Africana"
  },
  {
    "code": "CG",
    "name": "Congo"
  },
  {
    "code": "CH",
    "name": "Suíça"
  },
  {
    "code": "CI",
    "name": "Costa do Marfim"
  },
  {
    "code": "CK",
    "name": "Cook, Ilhas"
  },
  {
    "code": "CL",
    "name": "Chile"
  },
  {
    "code": "CM",
    "name": "Camarões"
  },
  {
    "code": "CN",
    "name": "China, República Popular"
  },
  {
    "code": "CO",
    "name": "Colômbia"
  },
  {
    "code": "CR",
    "name": "Costa Rica"
  },
  {
    "code": "CU",
    "name": "Cuba"
  },
  {
    "code": "CV",
    "name": "Cabo Verde, República de"
  },
  {
    "code": "CW",
    "name": "Curaçao"
  },
  {
    "code": "CX",
    "name": "Christmas, Ilha"
  },
  {
    "code": "CY",
    "name": "Chipre"
  },
  {
    "code": "CZ",
    "name": "Tcheca, República"
  },
  {
    "code": "DE",
    "name": "Alemanha"
  },
  {
    "code": "DJ",
    "name": "Djibuti"
  },
  {
    "code": "DK",
    "name": "Dinamarca"
  },
  {
    "code": "DM",
    "name": "Dominica, Ilha"
  },
  {
    "code": "DO",
    "name": "República Dominicana"
  },
  {
    "code": "DZ",
    "name": "Argélia"
  },
  {
    "code": "EC",
    "name": "Equador"
  },
  {
    "code": "EE",
    "name": "Estônia, República da"
  },
  {
    "code": "EG",
    "name": "Egito"
  },
  {
    "code": "EH",
    "name": "Saara Ocidental"
  },
  {
    "code": "ER",
    "name": "Eritreia"
  },
  {
    "code": "ES",
    "name": "Espanha"
  },
  {
    "code": "ET",
    "name": "Etiópia"
  },
  {
    "code": "FI",
    "name": "Finlândia"
  },
  {
    "code": "FJ",
    "name": "Fiji"
  },
  {
    "code": "FK",
    "name": "Falkland (Ilhas Malvinas)"
  },
  {
    "code": "FM",
    "name": "Micronésia"
  },
  {
    "code": "FO",
    "name": "Feroe, Ilhas"
  },
  {
    "code": "FR",
    "name": "França"
  },
  {
    "code": "GA",
    "name": "Gabão"
  },
  {
    "code": "GB",
    "name": "Reino Unido"
  },
  {
    "code": "GD",
    "name": "Granada"
  },
  {
    "code": "GE",
    "name": "Geórgia, República da"
  },
  {
    "code": "GF",
    "name": "Guiana Francesa"
  },
  {
    "code": "GG",
    "name": "Guernsey"
  },
  {
    "code": "GH",
    "name": "Gana"
  },
  {
    "code": "GI",
    "name": "Gibraltar"
  },
  {
    "code": "GL",
    "name": "Groenlândia"
  },
  {
    "code": "GM",
    "name": "Gambia"
  },
  {
    "code": "GN",
    "name": "Guiné"
  },
  {
    "code": "GP",
    "name": "Guadalupe"
  },
  {
    "code": "GQ",
    "name": "Guiné-Equatorial"
  },
  {
    "code": "GR",
    "name": "Grécia"
  },
  {
    "code": "GS",
    "name": "Ilhas Geórgia do Sul e Sandwich do Sul"
  },
  {
    "code": "GT",
    "name": "Guatemala"
  },
  {
    "code": "GU",
    "name": "Guam"
  },
  {
    "code": "GW",
    "name": "Guiné-Bissau"
  },
  {
    "code": "GY",
    "name": "Guiana"
  },
  {
    "code": "HK",
    "name": "Hong Kong"
  },
  {
    "code": "HM",
    "name": "Ilha Heard e Ilhas McDonald"
  },
  {
    "code": "HN",
    "name": "Honduras"
  },
  {
    "code": "HR",
    "name": "Croácia, República da"
  },
  {
    "code": "HT",
    "name": "Haiti"
  },
  {
    "code": "HU",
    "name": "Hungria, República da"
  },
  {
    "code": "ID",
    "name": "Indonésia"
  },
  {
    "code": "IE",
    "name": "Irlanda"
  },
  {
    "code": "IL",
    "name": "Israel"
  },
  {
    "code": "IM",
    "name": "Man, Ilha de"
  },
  {
    "code": "IN",
    "name": "Índia"
  },
  {
    "code": "IO",
    "name": "Território Britânico no Oceano Índico"
  },
  {
    "code": "IQ",
    "name": "Iraque"
  },
  {
    "code": "IR",
    "name": "Irã, República Islâmica do"
  },
  {
    "code": "IS",
    "name": "Islândia"
  },
  {
    "code": "IT",
    "name": "Itália"
  },
  {
    "code": "JE",
    "name": "Jersey"
  },
  {
    "code": "JM",
    "name": "Jamaica"
  },
  {
    "code": "JO",
    "name": "Jordânia"
  },
  {
    "code": "JP",
    "name": "Japão"
  },
  {
    "code": "KE",
    "name": "Quênia"
  },
  {
    "code": "KG",
    "name": "Quirguiz, República da"
  },
  {
    "code": "KH",
    "name": "Camboja"
  },
  {
    "code": "KI",
    "name": "Kiribati"
  },
  {
    "code": "KM",
    "name": "Comores, Ilhas"
  },
  {
    "code": "KN",
    "name": "São Cristóvão e Neves, Ilhas"
  },
  {
    "code": "KP",
    "name": "Coréia (do Norte), Rep. Pop. Democrática da"
  },
  {
    "code": "KR",
    "name": "Coréia (do Sul), República da"
  },
  {
    "code": "KW",
    "name": "Kuwait"
  },
  {
    "code": "KY",
    "name": "Cayman, Ilhas"
  },
  {
    "code": "KZ",
    "name": "Cazaquistão, República do"
  },
  {
    "code": "LA",
    "name": "Laos, Rep. Pop. Democrática do"
  },
  {
    "code": "LB",
    "name": "Líbano"
  },
  {
    "code": "LC",
    "name": "Santa Lúcia"
  },
  {
    "code": "LI",
    "name": "Liechtenstein"
  },
  {
    "code": "LK",
    "name": "Sri Lanka"
  },
  {
    "code": "LR",
    "name": "Libéria"
  },
  {
    "code": "LS",
    "name": "Lesoto"
  },
  {
    "code": "LT",
    "name": "Lituânia, República da"
  },
  {
    "code": "LU",
    "name": "Luxemburgo"
  },
  {
    "code": "LV",
    "name": "Letônia, República da"
  },
  {
    "code": "LY",
    "name": "Líbia"
  },
  {
    "code": "MA",
    "name": "Marrocos"
  },
  {
    "code": "MC",
    "name": "Mônaco"
  },
  {
    "code": "MD",
    "name": "Moldávia, República da"
  },
  {
    "code": "ME",
    "name": "Montenegro"
  },
  {
    "code": "MF",
    "name": "São Martinho (Parte Francesa)"
  },
  {
    "code": "MG",
    "name": "Madagascar"
  },
  {
    "code": "MH",
    "name": "Marshall, Ilhas"
  },
  {
    "code": "MK",
    "name": "Macedônia, Ant. Rep. Iugoslava"
  },
  {
    "code": "ML",
    "name": "Mali"
  },
  {
    "code": "MM",
    "name": "Myanmar (Birmânia)"
  },
  {
    "code": "MN",
    "name": "Mongólia"
  },
  {
    "code": "MO",
    "name": "Macau"
  },
  {
    "code": "MP",
    "name": "Marianas do Norte"
  },
  {
    "code": "MQ",
    "name": "Martinica"
  },
  {
    "code": "MR",
    "name": "Mauritânia"
  },
  {
    "code": "MS",
    "name": "Montserrat, Ilhas"
  },
  {
    "code": "MT",
    "name": "Malta"
  },
  {
    "code": "MU",
    "name": "Maurício"
  },
  {
    "code": "MV",
    "name": "Maldivas"
  },
  {
    "code": "MW",
    "name": "Malavi"
  },
  {
    "code": "MX",
    "name": "México"
  },
  {
    "code": "MY",
    "name": "Malásia"
  },
  {
    "code": "MZ",
    "name": "Moçambique"
  },
  {
    "code": "NA",
    "name": "Namíbia"
  },
  {
    "code": "NC",
    "name": "Nova Caledônia"
  },
  {
    "code": "NE",
    "name": "Níger"
  },
  {
    "code": "NF",
    "name": "Norfolk, Ilha"
  },
  {
    "code": "NG",
    "name": "Nigéria"
  },
  {
    "code": "NI",
    "name": "Nicarágua"
  },
  {
    "code": "NL",
    "name": "Países Baixos (Holanda)"
  },
  {
    "code": "NO",
    "name": "Noruega"
  },
  {
    "code": "NP",
    "name": "Nepal"
  },
  {
    "code": "NR",
    "name": "Nauru"
  },
  {
    "code": "NU",
    "name": "Niue, Ilha"
  },
  {
    "code": "NZ",
    "name": "Nova Zelândia"
  },
  {
    "code": "OM",
    "name": "Omã"
  },
  {
    "code": "PA",
    "name": "Panamá"
  },
  {
    "code": "PE",
    "name": "Peru"
  },
  {
    "code": "PF",
    "name": "Polinésia Francesa"
  },
  {
    "code": "PG",
    "name": "Papua Nova Guiné"
  },
  {
    "code": "PH",
    "name": "Filipinas"
  },
  {
    "code": "PK",
    "name": "Paquistão"
  },
  {
    "code": "PL",
    "name": "Polônia, República da"
  },
  {
    "code": "PM",
    "name": "São Pedro e Miquelon"
  },
  {
    "code": "PN",
    "name": "Pitcairn, Ilha De"
  },
  {
    "code": "PR",
    "name": "Porto Rico"
  },
  {
    "code": "PS",
    "name": "Palestina"
  },
  {
    "code": "PT",
    "name": "Portugal"
  },
  {
    "code": "PW",
    "name": "Palau"
  },
  {
    "code": "PY",
    "name": "Paraguai"
  },
  {
    "code": "QA",
    "name": "Catar"
  },
  {
    "code": "RE",
    "name": "Reunião, Ilha"
  },
  {
    "code": "RO",
    "name": "Romênia"
  },
  {
    "code": "RS",
    "name": "Servia"
  },
  {
    "code": "RU",
    "name": "Rússia, Federação da"
  },
  {
    "code": "RW",
    "name": "Ruanda"
  },
  {
    "code": "SA",
    "name": "Arábia Saudita"
  },
  {
    "code": "SB",
    "name": "Salomão, Ilhas"
  },
  {
    "code": "SC",
    "name": "Seychelles"
  },
  {
    "code": "SD",
    "name": "Sudão"
  },
  {
    "code": "SE",
    "name": "Suécia"
  },
  {
    "code": "SG",
    "name": "Cingapura"
  },
  {
    "code": "SH",
    "name": "Santa Helena"
  },
  {
    "code": "SI",
    "name": "Eslovênia, República da"
  },
  {
    "code": "SJ",
    "name": "Svalbard e Jan Mayen"
  },
  {
    "code": "SK",
    "name": "Eslovaca, República"
  },
  {
    "code": "SL",
    "name": "Serra Leoa"
  },
  {
    "code": "SM",
    "name": "San Marino"
  },
  {
    "code": "SN",
    "name": "Senegal"
  },
  {
    "code": "SO",
    "name": "Somália"
  },
  {
    "code": "SR",
    "name": "Suriname"
  },
  {
    "code": "SS",
    "name": "Sudão do Sul"
  },
  {
    "code": "ST",
    "name": "São Tomé e Príncipe, Ilhas"
  },
  {
    "code": "SV",
    "name": "El Salvador"
  },
  {
    "code": "SX",
    "name": "São Martinho (Parte Holandesa)"
  },
  {
    "code": "SY",
    "name": "Síria, República Árabe da"
  },
  {
    "code": "SZ",
    "name": "Suazilândia"
  },
  {
    "code": "TC",
    "name": "Turcas e Caicos, Ilhas"
  },
  {
    "code": "TD",
    "name": "Chade"
  },
  {
    "code": "TF",
    "name": "Terras Austrais e Antárticas Francesas"
  },
  {
    "code": "TG",
    "name": "Togo"
  },
  {
    "code": "TH",
    "name": "Tailândia"
  },
  {
    "code": "TJ",
    "name": "Tadjiquistão, República do"
  },
  {
    "code": "TK",
    "name": "Toquelau, Ilhas"
  },
  {
    "code": "TL",
    "name": "Timor Leste"
  },
  {
    "code": "TM",
    "name": "Turcomenistão, República do"
  },
  {
    "code": "TN",
    "name": "Tunísia"
  },
  {
    "code": "TO",
    "name": "Tonga"
  },
  {
    "code": "TR",
    "name": "Turquia"
  },
  {
    "code": "TT",
    "name": "Trinidad e Tobago"
  },
  {
    "code": "TV",
    "name": "Tuvalu"
  },
  {
    "code": "TW",
    "name": "Formosa (Taiwan)"
  },
  {
    "code": "TZ",
    "name": "Tanzânia, Rep. Unida da"
  },
  {
    "code": "UA",
    "name": "Ucrânia"
  },
  {
    "code": "UG",
    "name": "Uganda"
  },
  {
    "code": "UM",
    "name": "Pacífico, Ilhas do (Possessão dos EUA)"
  },
  {
    "code": "US",
    "name": "Estados Unidos"
  },
  {
    "code": "UY",
    "name": "Uruguai"
  },
  {
    "code": "UZ",
    "name": "Uzbequistão, República do"
  },
  {
    "code": "VA",
    "name": "Vaticano, Est. da Cidade do"
  },
  {
    "code": "VC",
    "name": "São Vicente e Granadinas"
  },
  {
    "code": "VE",
    "name": "Venezuela"
  },
  {
    "code": "VG",
    "name": "Virgens, Ilhas (Britânicas)"
  },
  {
    "code": "VI",
    "name": "Virgens, Ilhas (E.U.A.)"
  },
  {
    "code": "VN",
    "name": "Vietnã"
  },
  {
    "code": "VU",
    "name": "Vanuatu"
  },
  {
    "code": "WF",
    "name": "Wallis e Futuna, Ilhas"
  },
  {
    "code": "WS",
    "name": "Samoa"
  },
  {
    "code": "YE",
    "name": "Iêmen"
  },
  {
    "code": "YT",
    "name": "Mayotte"
  },
  {
    "code": "ZA",
    "name": "África do Sul"
  },
  {
    "code": "ZM",
    "name": "Zâmbia"
  },
  {
    "code": "ZW",
    "name": "Zimbábue"
  },
  {
    "code": "ZZ",
    "name": "Município não possui a informação no sistema próprio;"
  }
] as const;
